microsoft/accessibility-insights-action

- src/check-run/check-run-creator.spec.ts
- src/check-run/check-run-creator.ts
- src/content/strings.ts
- src/mark-down/__snapshots__/check-result-markdown-builder.spec.ts.snap
- src/mark-down/check-result-markdown-builder.ts
- src/utils/markdown-formatter.spec.ts
- src/utils/markdown-formatter.ts
> feat: move some content to fit the result view template

- .github/workflows/nodejs.yml
- action.yml
- package.json
- src/task-config.spec.ts
- src/task-config.ts
- yarn.lock
- Enable Code coverage using Codecov.
- Add ouputDire as an action input.
> chore: enable Code coverage using Codecov and add ouputDir as an action input

- action.yml
> chore: fix accessibility insights action name

- src/content/strings.ts
- src/ioc/setup-ioc-container.spec.ts
- src/mark-down/__snapshots__/check-result-markdown-builder.spec.ts.snap
- src/mark-down/check-result-markdown-builder.ts
Also added/removed period in the text according to the spec.
> chore: Added tests for setup ioc container

- README.md
> chore: redirect to dependabot.com for dependabot badge

- .github/pull_request_template.md
- license-check-and-add-config.json
- package.json
> chore: remove license from pull request template

- .dependabot/config.yml
- .prettierignore
- license-check-and-add-config.json
> chore: Add dependabot config

- package.json
- yarn.lock
Upgrade vulnerable packages to fix github alert
> fix: upgrade minimist to 1.2.2 and acorn to 7.1.1

- package.json
- yarn.lock
> fix: fixing security vulnerabilities

- package.json
- yarn.lock
Updates transitive dependency `@actions/http-client` to avoid https://github.com/advisories/GHSA-9w6v-m7wp-jwg4
> chore(deps): add a resolution to fix the security alert about @actions/http-client

- package.json
- yarn.lock
Update serialize-java package to fix CG alert
> chore: update serialize-java

- NOTICES.txt
This PR updates the bundled action:
- `dist/index.js` file produced by running `yarn build`
- NOTICES file produced via component governance
Validated [here](https://github.com/microsoft/accessibility-insights-docs/pull/369) (see link-name failure)
> feat(axe-core-4.0.2): update notices file and release

- package.json
Recent builds have been failing with a silent error for some time (presumably since webpack-cli last updated):
```
$ webpack --config ./webpack.config.js --colors
[webpack-cli] Unknown argument: --colors
```
> chore: fix build

- package.json
- yarn.lock
- Updated axe-core to 4.1.1
- Updated accessibility-insights-report to 4.0.0
- Updated accessibility-insights-scan to 0.6.0
> feat(axe-core-4.1.1): update axe-core, report, and ai-scan packages

- NOTICES.txt
Bumps NOTICES file, regenerating it against package.json/yarn.lock content as of commit 20fef4d73f92d0cbb7ab7f30e6ba1ec9c763bb54
> chore: update NOTICES file to match yarn.lock as of 20fef4d

- package.json
- yarn.lock
Component governance vulnerabilities fix
> Component governance vulnerabilities fix

- .github/workflows/nodejs.yml
- README.md
This completes the code changes for switching from master to main started with #518 and #519
> chore: update default branch refs from master to main

- dist/package.json
- webpack.config.js
Fix CredScan violations
Remove from webpack module with CredScan violations
> Fix CredScan violations

- dev/README.md
Added setup instruction to run action on Windows development environment
> Added Windows development support instructions

- dist/package.json
- package.json
- yarn.lock
Update cli npm version to include latest changes.
> Update cli npm version

- action.yml
- dev/github/workflows/accessibility-validation.yaml
- dist/index.js
- dist/package.json
- package.json
- src/local-file-server.spec.ts
- src/local-file-server.ts
- src/task-config.spec.ts
- src/task-config.ts
- yarn.lock
Added support of specify preferred localhost TCP port to use by website service
Remove node --prefix option
Fixed npm alert
> Added support of fixed localhost port

- docs/usage.md
This upload-artifact should be v2, not v2.0.0. I tried it here: https://github.com/karanbirsingh/test-ai-action/runs/2585678065?check_suite_focus=true
> fix: update usage.md because it refers to incorrect action

- NOTICES.txt
- dist/index.js
- dist/package.json
- dist/yarn.lock
- docs/usage.md
- package.json
Release version 2.1.1, including all of the most recent changes and a revised NOTICES.TXT file
4 Tests are failing on Windows machines. Not a new issue, as it occurs at v2.1.0 (and probably before but I didn't look for any earlier versions)
> chore(release): bump version to 2.1.1

- package.json
- yarn.lock
To address the CG issue we need to upgrade to css-what v 5.0.1 or above
> added resolution for css-what

- dist/package.json
- dist/yarn.lock
- package.json
- yarn.lock
> Updating the /dist folder to include the css-what fixes

- dist/yarn.lock
- docs/usage.md
- package.json
This PR preps for release 2.2.0:
- updating usage.md and package.json
After this gets merged we will generate a NOTICE file and update NOTICE.txt. Then we will release.
> chore: prep for release 2.2.0

- NOTICES.txt
Following up from #734 with the NOTICES file. We will validate and release next.
required for release
> chore: update NOTICES.txt for 2.2.0

- packages/ado-extension/ado-extension.json
- packages/ado-extension/jest.config.js
- packages/ado-extension/package.json
- packages/ado-extension/prepare-package-dir.js
- packages/ado-extension/src/ado-extension-test.spec.ts
- packages/ado-extension/src/index.ts
- packages/ado-extension/task.json
- packages/ado-extension/tsconfig.json
- yarn.lock
A follow up to #752 
This creates the ado-extension package in the monorepo, and we used the ado-prototype branch as a model. With this PR, the structure is now
```
- packages
- gh-action
- shared
- ado-extension
- ado-extension.json
- package.json
- prepare-package-dir.js (a file that runs several copy operations that moves files to the dist folder)
- task.json
- tsconfig.json
- jest.config.js
- src
- index.ts (for now, just console logs "Hello World")
- ado-extension-test-spec.ts (Sample test file)
- dist (ado-extension.json copy)
- pkg (idex.js, task.json, package.json, extension-icon copies)
```
Things to note: 
- We can potentially look to use webpack instead of `prepare-package-dir.js` and this can be done in an upcoming PR
- We tested these changes using the old publisher identity …
> feat(ado/infra): Creating the ado-extension package

- packages/shared/package.json
- yarn.lock
Updates axe-core and related packages.
feature work.
N/A
> feat(axe-core-4.3.2): bump report and scan packages

- packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
- packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts
This PR follows up on #828 by improving `AdoPullRequestCommentCreator` in two ways:
1. It improves the detection of the original comment by matching with the full product title string rather than just "Accessibility Insights"
2. It updates the original comment with the results of subsequent scans
Making `AdoPullRequestCommentCreator` more robust
We still need to add handling for different auth schemes
> feat(mvp-ado-extension-behavior): Improve AdoPullRequestCommentCreator behavior

- docs/ado-extension-usage.md
Update the ADO extension docs to include `displayName`, update the version number to 1, and add the `always()` condition to the publish step.
Improve docs clarity and accuracy
n/a
> feat(mvp-ado-extension-behavior): Minor ado extension docs improvements

- packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
- packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts
Update UTs to include the failOnAccessibilityError case
> feat(mvp-ado-extension-behavior): Update UTs to include the failOnAccessibilityError case

- packages/ado-extension/ado-extension.json
- packages/ado-extension/package.json
- packages/ado-extension/task.json
Update `task.json` and `ado-extension.json` to show v1.0.0 
For release
> feat(mvp-ado-extension-behavior): update version number to 1.0.0

- pipelines/canary-release.yaml
- pipelines/package-vsix-file.yaml
- pipelines/prod-release.yaml
- pipelines/publish-vsix-file.yaml
- pipelines/release-template.yaml
Change visibility in yaml files for public (beta) release
> chore: change visibility in yaml files

- docs/ado-extension-overview.md
- packages/ado-extension/ado-extension.json
- packages/ado-extension/prepare-package-dir.js
- pipelines/canary-release.yaml
- pipelines/prod-release.yaml
* Add overview.md for extension page in VS Marketplace
* Add preview flag for canary, staging, and prod. Visibility of extension is still private
> feat: add overview.md and preview flag

- package.json
- yarn.lock
We've accumulated several resolution statements that aren't strictly necessary. I went through the package.json file, deleting one resolution file at a time, then running `yarn install`, and evaluating the difference after each change. I found 5 lines that seem like they are no longer necessary.
Reduce the debt represented by the resolutions statements
> chore: Clean resolutions

- package.json
- packages/shared/package.json
- packages/shared/src/console-output/__custom-snapshots__/axe-descriptions.snap.md
- packages/shared/src/mark-down/__custom-snapshots__/axe-descriptions.snap.md
- yarn.lock
This updates dependencies for axe-core and accessibility-insights-report
feature work
These are dependencies in the ADO Extension as well, but they're ones that we also want updated before the next ADO Extension release.
> feat(ado-gha-axe-core): update axe-core and accessibility-insights-report

- package.json
- yarn.lock
Remove dependency resolutions that are no longer needed
Clean up package.json
> chore: remove unneeded dependency resolutions

- docs/ado-extension-usage.md
This adds example pipelines to our ADO usage documentation.
This does not impact the GH Action.
Improved documentation and addresses #1066 
> feat(ado-improvements): add example pipelines to usage documentation

- pipelines/build.yaml
This PR adds CodeQL as part of the build Pipeline jobs for data flow and control flow analysis.
Onboard into the new OpenQL 3000 auto-injected extension, to improve our workflow to discover vulnerabilities across our codebase.
I decided to add CodeQL as a new job within our build Pipeline so that it doesn't interrupt previous jobs.
Image of the new job added into build pipeline:
Example of the updated build pipeline run:
https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=38666&view=results
> chore: Adding CodeQL check into build pipeline

- .github/ISSUE_TEMPLATE/feature_request.md
I noticed the feature request issue template was not appearing as an option to select. I think this is because there is a empty line at the start of the markdown file.
I would like to request a feature 😇
> chore: Fix feature request issue template

- packages/shared/package.json
This consumes the new scan package with the fix for the auth flow.
consume changes from scan package
This pulls the new package in for both the ADO Extension and the GH action, but the code doesn't execute on the GH side as there is no auth infrastructure.
> chore: consume new scan package

- package.json
Remove yarn resolutions that are no longer necessary. Tested by removing the items then confirming that `yarn install` creates no changes in `yarn.lock`
Reduce tech debt that lurks in the resolutions.
> chore: Remove unused resolutions

- packages/shared/package.json
- yarn.lock
update accessibility insights scan package to latest version to fix canary validation pipeline issues.
> chore(deps): update accessibility insights scan package to latest

- pipelines/prod-release.yaml
Add dependency between different stages of the pipeline to run them sequentially with 1ES template
> fix: update dependency tree in production release pipeline
