microsoft/accessibility-insights-action

package.json
yarn.lock

Update report package to version 2.0.0 (required with update to axe-core 4.0.1, since the old reporter package references axe-core rules that have been removed in 4.0.1)

Update report package to 2.0.0 (necessary with axe-core 4.0.1)

---

package.json

Make sure we have the packages in the right section of package.json (either dependencies or devDependencies) so we can generate an accurate NOTICE file

chore: rearrange dependencies and devDependencies

---

package.json
yarn.lock

Forces `apify-shared` to >= 0.5 like `accessibility-insights-service` [here](https://github.com/microsoft/accessibility-insights-service/blob/535202c0981d9b24cef1dbd4708d9e52dca7ef00/package.json#L65). This is to [remove a reference to `slugg`](https://github.com/apify/apify-shared-js/issues/76), which doesn't have a license listed. I checked to see if a resolution in `packages/cli/package.json` worked, but yarn didn't pick it up.
An upcoming PR will release with an updated notice file.

deps: add resolution to force apify-shared to >= 0.5

---

.gitignore
src/scanner/scanner.spec.ts
src/scanner/scanner.ts
webpack.config.js

This updates our build process per CELA guidance to avoid bundling MPL code into the same files as non-MPL code for distribution.

fix: avoid bundling MPL dependencies into same file as non-MPL code

---

package.json
yarn.lock

Resolves a CG/GitHub Security alert for CVE-2020-28168

chore: force an axios update to avoid CVE-2020-28168

---

src/scanner/scanner.spec.ts
src/scanner/scanner.ts

Fixes a bug introduced in #395 where resolving axe.min.js doesn't work correctly when the bundled index.js is run from a working directory that isn't its own directory (because `require.resolve` returns a relative path as #395 used it).

fix: prevent error when injecting axe.min.js introduced in #395

---

package.json
yarn.lock

In previous PR #390, we updated the version of `accessibility-insights-report` in the dependencies section of `package.json`, but missed updating the `resolutions` entry for the same package. This caused the versions of -report used in practice vs expected by the scan package to mismatch, which resulted in a very confusing looking error during execution of the action:
```
Exception thrown in action:  TypeError: Cannot read property 'semanticColors' of undefined
at exports.getStyles (/home/runner/work/_actions/microsoft/accessibility-insights-action/release-20200105/dist/index.js:56491:32)
at Object.concatStyleSetsWithProps (/home/runner/work/_actions/microsoft/accessibility-insights-action/release-20200105/dist/index.js:7352:56)
at _styles …
```

fix: prevent TypeError during report generation by updating ai-report resolution to match dependency (#401)

---

jest.config.js

Currently, `yarn test` (both locally and in CI builds) shows the following warning:
```
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
```
This PR fixes the warning

chore: fix ts-jest warning during yarn test

---

package.json
yarn.lock

Dependabot cannot update marked to a non-vulnerable version
The latest possible version that can be installed is 1.2.9 because of the following conflicting dependency:
accessibility-insights-scan@0.6.0 requires marked@^1.1.0 via a transitive dependency on apify-shared@0.5.0
The earliest fixed version is 2.0.0.

Using resolutions to fix marked Dependabot alert

---

.github/workflows/nodejs.yml
CONTRIBUTING.md
README.md

This PR establishes our versioning strategy (based on the standard GitHub actions documentation) and documents both a release process based on it and usage in the README to consume via the new strategy.
Two motivating factors:
* Enable a more forwards-compatible versioning strategy while there are still few consumers
* Unblock renaming the default branch from master to main
@AhmedAbdoOrtiga and I discussed a few options for release strategy before settling on this. The most challenging tradeoff was whether to stick with `v0.x.y` (to indicate that the package is not considered stable) or to start from `v1` (to avoid user confusion when the semver level allowing breaking changes switches from minor to major during a `v0.1` to `v1` switch). We decided to go with `v1` and trust that the …

chore: document release strategy in preparation for default branch rename

---

NOTICES.txt
yarn.lock

The package underscore from 1.13.0-0 and before 1.13.0-2, from 1.3.2 and before 1.12.1 are vulnerable to Arbitrary Code Execution via the template function, particularly when a variable property is passed as an argument as it is not sanitized.
Fix vulnerable packages

Update underscore package to a non vulnerable version

---

.github/workflows/nodejs.yml
package.json
yarn.lock

Use npm Codecov package instead of the Codecov action since action uses bash uploader and bash uploader might be affected by a security vulnerability
Avoid security vulnerabilities.

chore: Use Codecov npm pakcage instead of the GitHub action 

---

action.yml
src/scanner/scanner.spec.ts
src/scanner/scanner.ts
src/task-config.spec.ts
src/task-config.ts

* Added `url` input to action.yml and corresponding getUrl to task-config.ts
* Modified scanner.ts to use remote url as the scan url if `url` is specified in the input. If `url` is not specified, start the file server and use scan url relative path for the scan url.
Addresses WI: # 1837995
Verified the following scenarios:
* [Added `url` input in test repo](https://github.com/lisli1/test-action/runs/2452665414?check_suite_focus=true) and checked that the resulting artifact scan report and an exported report from running FastPass on the same URL had the same results
* [Removed `url` from test repo](https://github.com/lisli1/test-action/runs/2452718082?check_suite_focus=true) to check that the local file is scanned when the `url` input is not present
* [Added empty string `''` for `url` …

feat(gh-action-crawling): add scanning of remote URL

---

action.yml
src/task-config.spec.ts
src/task-config.ts

This PR adds crawling options similar to [accessibility-insights-scan](https://www.npmjs.com/package/accessibility-insights-scan). It adds:
- url
- maxUrls
- discoveryPatterns
- inputFile
- inputUrls
tested [here](https://github.com/karanbirsingh/test-a11y-action/runs/2463027566?check_suite_focus=true) (action accepts `max-urls` in test)
We want to pass these along to the crawler.
In the CLI we do some parsing and error checking:
- https://github.com/microsoft/accessibility-insights-service/blob/main/packages/cli/src/cli.ts#L28
- https://github.com/microsoft/accessibility-insights-service/blob/main/packages/cli/src/crawler-parameters-builder.ts
We might want to expose some of this from AICrawler and reuse it. Otherwise in a follow-up PR we can reimplement some of these error checks.

feat(gh-action-crawling): add crawling options to action input metadata

---

dist/package.json
package.json
yarn.lock

Force resolution of apify-shared to version 0.5.0 or higher
This will remove a transitive dependency on an unmaintained, licenseless package

chore: apify-shared 0.5.0

---

.github/workflows/nodejs.yml

By default our repo's GitHub token has [permissive access](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token). A recent workflow in this repository shows the following permissions:
```
GITHUB_TOKEN Permissions
Actions: write
Checks: write
Contents: write
Deployments: write
Discussions: write
Issues: write
Metadata: read
Packages: write
PullRequests: write
RepositoryProjects: write
SecurityEvents: write
Statuses: write
```
I changed the default scope to be read-only. This works for builds & unit tests, but the accessibility action requires some special write permissions. This PR adds the required permissions explicitly.
Fix self-validation now that the default GitHub token access is read-only.
Here are some helpful docs: …

chore: restore required GITHUB_TOKEN permissions when self-validating the action

---

action.yml

https://github.com/actions/runner/issues/665 mentions that input arguments are not implicitly mapped to environment variables in composite action steps. This `action.yml` file contained an inline script to map the environment variables. This PR replaces the inline script with the `env` context.
This is simpler and helps protect the action from possible future runtime injection in the bash script (imagine the script included something like `${{ github.event.pull_request.title }}`.

chore: Map environment variables using 'env' context instead of inline bash script

---

action.yml
dist/index.js
dist/yarn.lock
docs/usage.md
src/scanner/scanner.spec.ts
src/scanner/scanner.ts
src/task-config.spec.ts
src/task-config.ts

This PR allows the user to override the default scan timeout of 90 seconds.
You can see a test run with 1 second here:
- [usage code](https://github.com/karanbirsingh/my-website/commit/d5a37cc4f703d648757770b1c973eb44b16b8f4d)
- [execution logs](https://github.com/karanbirsingh/my-website/runs/3072065050?check_suite_focus=true)
addresses #714 , some webpages take longer to scan especially with crawling

fix: allow user to configure scan timeout duration

---

package.json
yarn.lock

The current version depends on a vulnerable version of sshpk. Updated to 1.3.1

updating http-signature version

---

src/task-config.spec.ts

Running tests on a Windows machine fails every time because the tests are hardcoded for linux. The _non-test_ code does the right thing on any OS (including Window), but the _test code_ doesn't know how to handle non-linux OS. This simply teaches the test code to expect the non-test code's behavior.
Not everyone does their dev work on linux machines.

chore: Allow tests to run on Windows machines

---

.prettierignore
dev/website-root/index.html
dist/index.js
dist/yarn.lock
jest.config.js
license-check-and-add-config.json
package.json
src/jest-setup.ts
src/mark-down/__custom-snapshots__/axe-descriptions.snap.md
src/mark-down/__snapshots__/markdown-formatter.spec.ts.snap
src/mark-down/markdown-formatter.spec.ts
src/mark-down/markdown-formatter.ts
src/mark-down/result-markdown-builder.spec.ts
src/mark-down/result-markdown-builder.ts
yarn.lock

This PR escapes the < character in axe-core rule IDs and descriptions. The GitHub action (and later, the ADO extension) both render markdown. Without this change, strings like `<img>` or `<video>` are (unsuccessfully) rendered as actual HTML images or videos in both GitHub and Azure DevOps.
We replace instances of `<` with `\<` so that tags are not rendered in their HTML forms. GitHub describes some backslash-escaped values [here](https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf). While HTML tags aren't listed, experimentally this change works well. Azure DevOps [also describes backslash-escaped values](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#ignore-or-escape-markdown-syntax-to-enter-specific-or-literal-characters). …

fix: escape special characters in markdown

---

dev/release-strategy.md

Discuss and document how we intend to manage our releases in a way that supports multiple versions and allows users to easily control what version of the action they use. In turn, this will inform the actions taken by the build and release pipelines.
Flush out assumptions
- [n/a] (after PR created) The `Accessibility Checks (pull_request)` check should fail. All other checks should pass.

feat(ado/infra): Document release strategy

---

pipelines/build.yaml

Remove build task before SDT tasks.
Exclude node_modules & dist from SDT.

feat(ado/infra): Run SDT only on source code

---

dev/README.md

Remove release instruction from the repo.
The release process was automated and the instruction to use our pipelines was moved internally.

feat(ado/infra): Remove release instruction 

---

packages/RELEASE_COMMIT.md
pipelines/build.yaml

Generate the release commit info in the build pipeline.

feat(ado/infra):  Generate release commit info during build

---

pipelines/build.yaml

This PR publishes `packages/ado-extension/dist` as an artifact every time the CI build runs. This allows us to create a release pipeline that consumes these artifacts and packages/publishes a VSIX file.
I limit this build to run on CI (our tests for this repository are in GitHub workflows) - doesn't make sense to create artifacts or run SDT on PRs.
I also combined the test & lint jobs for now (PublishBuildDrops is still the longest) and made sure we build before running tests (otherwise consumers of @accessibility-isnights-action/shared can't import properly).
Lastly, I add a condition to SDT so it only runs on the main branch. This lets us queue CI builds on test branches for test releases without modifying the pipeline structure too much. May come back and change this if we separate SDT …

feat(ado/infra): publish ado-extension distribution folder each build

---

packages/gh-action/package.json
packages/gh-action/src/check-run/check-run-creator.spec.ts
packages/gh-action/src/check-run/check-run-creator.ts
packages/gh-action/src/index.ts
packages/gh-action/src/ioc/gh-ioc-types.ts
packages/gh-action/src/ioc/setup-ioc-container.spec.ts
packages/gh-action/src/ioc/setup-ioc-container.ts
packages/gh-action/src/pull-request/pull-request-comment-creator.spec.ts
packages/gh-action/src/pull-request/pull-request-comment-creator.ts
packages/gh-action/src/task-config/gh-task-config.spec.ts
packages/gh-action/src/task-config/gh-task-config.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/ioc/ioc-types.ts
packages/shared/src/ioc/setup-ioc-container.spec.ts
packages/shared/src/ioc/setup-ioc-container.ts
packages/shared/src/local-file-server.spec.ts
packages/shared/src/local-file-server.ts
packages/shared/src/progress-reporter/all-progress-reporter.spec.ts
packages/shared/src/progress-reporter/all-progress-reporter.ts
packages/shared/src/report/consolidated-report-generator.ts
packages/shared/src/scanner/crawl-argument-handler.ts
packages/shared/src/scanner/scan-url-resolver.ts
packages/shared/src/scanner/scanner.ts
packages/shared/src/task-config.ts
yarn.lock

Refactor the code to setup IoC using inversify and move all action related code out of shared in action.
Make it easier to integrate and maintain the code so it'd be easy to integrate ADO code.

feat(ado/infra): Refactor to set IoC using inversify

---

pipelines/prod-release.yaml

Move the create GitHub release job to be inside the publish so it'd need an approval to run.
Guard the prod tasks by an approval request before running.

feat(ado/infra): Refactor ADO prod publish pipeline

---

pipelines/prod-release.yaml

This PR allows us to override the staging / prod versions separately in the ADO extension release. I encountered a situation in which the staging version was x.0.1 but the production version was x.0.0 (the production release had been abandoned). In this scenario releasing to x.0.1 fails because staging already had that version (the pipeline used the same version for both).
Now only production requires explicit version numbers - staging can simply increment if not specified. It means that the version numbers for staging/production might be different; the alternative is to unlist old versions if needed, or skip version numbers if one was abandoned.
This PR also changes the GitHub releases to be drafts. This gives us time to review formatting before publishing.
simplify release process

feat(ado/infra): modify release pipeline to allow separate staging/prod versions

---

pipelines/prod-release.yaml

This PR allows us to create a release draft before publishing the ADO extension to prod, the tag won't be created before the user publish the draft manually.

feat(ado/infra): modify release pipeline to create release draft before publishing to Prod

---

packages/ado-extension/src/ioc/setup-ioc-container.spec.ts
packages/ado-extension/src/ioc/setup-ioc-container.ts
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/shared/src/task-config.ts

This PR adds ado-task-config to add TaskConfig class for the ADO extension and sets up the IoC for it.
Next PR should add those task configs to the task.json

feat(ado/behavior): Add ADOTaskConfig

---

packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json

Add the scanner/crawler inputs to the task config inputs.

feat(ado/behavior): Add scanner/crawler inputs to the ADO task.json config

---

packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json

This PR adds the optional `failOnAccessibilityError` and `repoServiceConnectionName` inputs to our task.json and task-config files.
We'll use these in future PRs for this feature. 
n/a

feat(mvp-ado-extension-behavior): Add optional inputs to task.json and config

---

packages/ado-extension/src/ado-extension.ts
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/tsconfig.json
packages/shared/src/task-config.ts

Enable `strictNullChecks` in ado-extension
WI 1871859
Left out enabling strictNullChecks for shared and gh-action to reduce size of PR

feat(mvp-ado-extension-behavior): enable strictNullChecks in ado-extension

---

packages/ado-extension/src/ioc/ado-ioc-types.ts
packages/ado-extension/src/ioc/setup-ioc-container.spec.ts
packages/ado-extension/src/ioc/setup-ioc-container.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts

This PR introduces `AdoPullRequestCommentCreator`, ported over from the prototype, and sets it up with the IoC container. 
We'll need this to comment on ADO pull requests.
Future PRs in this feature will add:
- Handling for the different auth schemes supported and access the appropriate params
- Improving the comment detection logic
- Updating the existing comment
- Wiring this up

feat(mvp-ado-extension-behavior): Introduce AdoPullRequestCommentCreator

---

packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts

Strict null checks were enabled in #829 but not in #828. They were merged at roughly the same, so the build broke. This PR fixes the build by adapting #829's changes to work with strictNullChecks.
Fixes main
n/a

fix: Fix issues from strictNullChecks merge

---

packages/ado-extension/package.json
packages/ado-extension/prepare-package-dir.js
packages/ado-extension/src/ado-extension.ts
packages/ado-extension/src/module-name-mapper.ts
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/webpack.config.js

This PR wires up the ADO extension parts.
This was tested in ADO for both comments and report generation.
In this PR i had to switch to webpack because the shared library wasn't found while running the action.
Get the extension to work in ADO PRs/CI

feat(mvp-ado-extension-behavior): Wire Up ADO extension

---

packages/ado-extension/task.json
pipelines/build.yaml

This PR disables e2e and removes the GitHub repo token from the task inputs.
Get the pipeline to work till 'azure-pipeline-task-lib' team reply to the webpack [issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/794).
Remove the GH repo token from user interface till we add its functionality.

feat(mvp-ado-extension-behavior): Disable e2e/ Remove the GH repo token from the task inputs

---

README.md
docs/ado-extension-usage.md
docs/gh-action-usage.md

* Added documentation for using the ADO extension, `docs/ado-extension-usage.md`
* Renamed the GitHub Action usage document for consistency, `docs/usage.md` to `docs/gh-action-usage.md`
Addresses WI 1871864

docs(mvp-ado-extension-behavior): ADO extension usage

---

packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts

This PR adds support for service connections using basic auth to `AdoPullRequestCommentCreator`. Based on [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#azure-repos), I don't believe that we need to support certificate based auth.
Follows up on #828 to support necessary auth schemes
Modelled after the [service connection handler in the ado pipelines tasks sample repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/artifacts-common/serviceConnectionUtils.ts).

feat(mvp-ado-extension-behavior): Add support for basic auth in AdoPullRequestCommentCreator 

---

packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts

This PR updates how we show the comment in the ADO PR.
The extesnsion will:
- Create a new comment thread if none exists.
- Add a new comment for the latest run and keep the previous run details in a below comment.

feat(mvp-ado-extension-behavior): Show previous comment

---

packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts

The change in #846 should have called `toLowerCase` on the auth scheme but did not. This PR fixes that. While in the area, it also adds suppression for some CredScan false positives.
Fixes authentication support
- The [service connection handler in the ado pipelines tasks sample repo](https://github.com/microsoft/azure-pipelines-tasks/blob/master/common-npm-packages/artifacts-common/serviceConnectionUtils.ts) this was modelled on calls `toLowerCase`.
- [Test use of extension here](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=26640&view=results)

feat(mvp-ado-extension-behavior): Fix auth switch by using toLowerCase

---

packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/gh-action/action.yml
packages/gh-action/src/task-config/gh-task-config.spec.ts
packages/gh-action/src/task-config/gh-task-config.ts
packages/shared/src/task-config.ts

Add Baseline input parameter for GH action and ADO extension.
Get the Action repo side ready to consume the scanner package after adding the baseline feature.
Adding two new parameter:
1. Baseline:  Generate Baseline if true.
2. Baseline file path: Path to existing baseline file, will generate delta between the generated one and the old one if exists.

feat(baseline-implementation): Add Baseline input parameters

---

packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/pull-request/ado-pull-request-comment-creator.ts
packages/shared/src/baseline-types.ts
packages/shared/src/progress-reporter/all-progress-reporter.spec.ts
packages/shared/src/progress-reporter/all-progress-reporter.ts
packages/shared/src/progress-reporter/progress-reporter.ts

* Added baseline-types.ts file (same as the one in [scan package PR](https://github.com/microsoft/accessibility-insights-service/pull/1743/files#diff-b8f7a3755b9dca11d1158b4ca3b87c4a6fdb8fcf25753d3da383bba065ef4d0d), will remove after scan package is released)
* Added BaselineEvaluation to progress-reporter to be used by ADOPullRequestCommentCreator
* Throw error if baselineFile was specified and there are suggested changes, implying that there are new failures that aren't currently in the baseline
Part of feature work
This PR doesn't include updating the PR comments to include baseline details; leaving that for a future PR.

feat(pr-baseline-2): enforce workflow with baseline

---

packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/gh-action/action.yml
packages/gh-action/src/task-config/gh-task-config.spec.ts
packages/gh-action/src/task-config/gh-task-config.ts
packages/shared/src/scanner/crawl-argument-handler.ts
packages/shared/src/task-config.ts
yarn.lock

Add singleWorker option in the GH Action/ ADO extension side.
Getting deterministic result for the baselining.
singleWorker and maxUrls will be used to check if the result is deterministic or not.

feat(baseline-implementation): Add singleWorker Option

---

packages/ado-extension/src/ado-artifacts-info-provider.spec.ts
packages/ado-extension/src/ado-artifacts-info-provider.ts

All characters in the artifact URLs need to be escaped so that browsers can handle them gracefully. This leverages the [URL class](https://developer.mozilla.org/en-US/docs/Web/API/URL) to generate proper escape sequences. This might be a case where it makes sense to review it by commit. The first commit adds the code, and the second commit is just whitespace changes from running prettier.
PR baselining feature

feat(pr-baseline-2): Escape artifact url

---

packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.spec.ts
packages/shared/src/mark-down/result-markdown-builder.ts

Fixes the failure counts showing in the ADO PR comments. There was some refactoring done as well in result-markdown-builder.ts and its corresponding test file.
Addresses #945 
PR comment screenshots:
1. Baseline file configured, no baseline file added to repo
2. Generated baseline file from (1) added to the repo, with previous comment below it as a child comment
3. Baseline file with fewer failure instances than found in current scan (scenario where errors were introduced)
4. Baseline file with more failure instances than found in current scan (assume errors were fixed)
5. Removed baselineFile input from yml (baseline not configured)

fix(ado-extension): failure counts in PR comment

---

packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.spec.ts
packages/shared/src/mark-down/result-markdown-builder.ts

As called out in #959, PR comments are wrong in cases where some (but not all) baseline failures are fixed in a PR. This change adds the corrected PR comments. It also includes a minor tweak to use more consistent output of section gaps in the output file. 
The summary of fixed violations only lists the rule and the count, since that's all we get from the diff engine. No rule description is consistently available.
Address #959 
At the moment, it feels like each method that adds text needs to be too aware of its location within a section. I have an idea for how to improve this, but I want to keep this PR relatively small and focused, then the refactoring can be in a separate PR.
open .

fix: Add missing PR scenarios

---

.github/dependabot.yml
package.json
packages/shared/src/progress-reporter/progress-reporter.ts
yarn.lock

This PR replaces https://github.com/microsoft/accessibility-insights-action/pull/969 , which needed a manual change.
I tried to pull in marked-terminal as well, but ran into issues described here: https://github.com/microsoft/accessibility-insights-action/pull/993#issuecomment-1005302270 so I updated our `dependabot.yml`.
Settle on proper versions for marked*
I tested this change by:
- creating a simple `LoggerReporter` that traces the markdown result and adding it to the IOC container
- running `npx cross-env ACT=true INPUT_URL=https://markreay.github.io/AU/before.html INPUT_SCANTIMEOUT=90000 INPUT_maxurls=5 INPUT_outputDir=_accessibility-reports yarn start` in `packages/ado-extension`
I got the following output:
```
[Trace][info] === Scan report saved successfully as …
```

chore(deps): update @types/marked and limit marked-terminal updates

---

license-check-and-add-config.json

`yarn precheckin` is broken on a mac, since building and testing creates a `.DS_Store` file that then fails the license check with the following error:
```
✗ License not found in .DS_Store
✗ License not found in dev/.DS_Store
✗ License not found in packages/.DS_Store
✗ License not found in dev/website-root/.DS_Store
✗ License not found in packages/ado-extension/.DS_Store
✗ License not found in packages/shared/.DS_Store
```
While fixing this, I also noticed that we still exclude NOTICES.TXT from license checks. This file was removed a while back, so there's no reason to still have it in the license exclusion list.
Support `yarn precheckin` from a mac
- [n/a] Addresses an existing issue

chore: Update files to ignore for license check

---

README.md

@RobGallo suggested moving the dev docs earlier in the README. The original spot was after the Contributing text, which is highly standardized across repos, so it's easy to assume there's nothing afterwards. I noticed that Contributing.md already contained the relevant license text so I removed the duplicate.
make it easier to find dev docs
n/a

chore: move the developer docs earlier in the README

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_question.md
license-check-and-add-config.json

In particular, dependabot requires these labels and we also use the labels to sort and triage bugs.

Chore: Add issue templates to the Action repo

---

.eslintrc.js
packages/ado-extension/package.json
packages/ado-extension/scripts/local-overrides.json
packages/ado-extension/scripts/run-locally.js

It can be difficult to debug the ADO extension locally. We can run `dist/pkg/index.js`, but we haven't been mapping input variables into the environment.
This PR adds a script so that we can more easily run the extension locally. It's not a full substitute for running in an agent environment - but it can be helpful in some scenarios.
Running `yarn start` will run the bundled `index.js` script with the following task inputs:
- any default values from [task.json inputs](https://github.com/microsoft/accessibility-insights-action/blob/main/packages/ado-extension/task.json)
- any additional values in `local-overrides.json` (these take precedence)
Here is the output I see when I run `yarn start`:
```
PS C:\Users\karansin\accessibility-insights-action\packages\ado-extension> yarn start
yarn run …
```

chore: add script to help run ADO extension locally

---

packages/shared/package.json
yarn.lock

This PR consumes the change in https://github.com/microsoft/accessibility-insights-web/pull/5145 so that we no longer see a React warning about missing keys in our execution logs.
Addresses part of #950

feat(ado-improvements-1): upgrade to report@4.2.1 package to take advantage of better log output

---

packages/ado-extension/webpack.config.js
packages/gh-action/webpack.config.js
packages/shared/package.json
yarn.lock

As called out in #950, the current logs include warnings about missing peer dependencies. This PR adds the peer dependencies to the generated package.json files so that the warnings don't occur.
Part of feature (reduce logging noise)
<details>
<summary>
Snippet of output BEFORE the change, showing 14 warnings of unmet peer dependencies
</summary>
```
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "accessibility-insights-report > office-ui-fabric-react@7.98.1" has unmet peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "accessibility-insights-report > office-ui-fabric-react@7.98.1" has unmet peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning "accessibility-insights-report > office-ui-fabric-react > @fluentui/react-focus@7.18.1" has unmet peer …
```

feat(ado-improvements-1): Add types to generated package.json

---

packages/shared/src/output-hooks/stdout-transformer.spec.ts
packages/shared/src/output-hooks/stdout-transformer.ts

If #1030, we changed stdout's default behavior to prefix ##[debug] to a string unless a special case existed to override the default. Unfortunately, I overlooked how 3 scanner-generated strings were exempted from the ##[debug] tag in #950's suggested output:
```
Processing page http://localhost:5858/
Discovered 2 links on page http://localhost:5858/
Found 3 accessibility issues on page http://localhost:5858/
```
This also streamlines the unit test that checks for unmodified output, so that the string only needs to be specified once.
Feature work
Before this change:
```
##[debug] Processing page https://markreay.github.io/AU/before.html
##[debug] Discovered 4 links on page https://markreay.github.io/AU/before.html
##[debug] Found 4 accessibility issues on page …
```

feat(ado-improvement-1): Exclude some strings that shouldn't have debug prefix

---

packages/ado-extension/src/install-runtime-dependencies.ts

As requested in #950, this adds a group tag for the ADO extension around the process of installing runtime dependencies. 
Output before this change:
```
installing runtime dependencies...
[1/4] 🔍  Resolving packages...
// Warnings omitted for brevity
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
```
Output after this change:
```
##[group]Installing runtime dependencies
[1/4] 🔍  Resolving packages...
// Warnings omitted for brevity
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
##[endgroup]
```
Improve logging as requested in #950
This changes _only_ the ADO experience. The Action experience already has this broken out as a separate …

feat(ado-improvements-1): Add group around installing dependencies

---

.github/dependabot.yml
packages/shared/package.json
yarn.lock

Revert #1043 and #1044 because the components, which moved @types/react and @types/react-dom from 16.X to 17.X. We have packages that are pinned to 16.X, so this leads to warnings when installing:
```
warning "accessibility-insights-report > office-ui-fabric-react@7.98.1" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "accessibility-insights-report > office-ui-fabric-react@7.98.1" has incorrect peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning "accessibility-insights-report > office-ui-fabric-react > @fluentui/react-focus@7.18.1" has incorrect peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "accessibility-insights-report > office-ui-fabric-react > @fluentui/react-focus@7.18.1" has incorrect peer dependency "@types/react-dom@>=16.8.0 <17.0.0". …
```

(chore): Revert upgrades to V17.X of react types

---

packages/ado-extension/src/ado-extension.ts
packages/ado-extension/src/install-runtime-dependencies.ts
packages/ado-extension/src/ioc/setup-ioc-container.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.spec.ts
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.ts
packages/gh-action/src/console/console-comment-creator.spec.ts
packages/gh-action/src/console/console-comment-creator.ts
packages/gh-action/src/index.ts
packages/shared/src/exit-code.ts
packages/shared/src/index.ts
packages/shared/src/progress-reporter/all-progress-reporter.spec.ts
packages/shared/src/progress-reporter/all-progress-reporter.ts
packages/shared/src/progress-reporter/progress-reporter.ts
packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

As called out in #950, we throw an `Error` if a scan fails, then we log the `Error` twice. To a user, it looks like our tool has crashed, when in reality it's an accessibility error that the user should fix. This PR does the following to improve this:
1. Some implementations of `ProgressReporter.failRun` used to throw an Error to force the program to fail. The new code merely sets a flag in `ProgressReporter.failRun`, then a new API, `ProgressReporter.didScanSucceed`, serves as an indicator of whether or not the scan succeeded.
2. Code that called `ProgressReporter.failRun` with a message is now responsible for logging the error message via `Logger.logError` or `Logger.trackException`, depending on the circumstance. With this change order of the `ProgressReporter` objects no longer …

feat(ado-improvements-1): Refactor reporter errors

---

packages/ado-extension/src/output-hooks/ado-stdout-transformer.spec.ts
packages/ado-extension/src/output-hooks/ado-stdout-transformer.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/shared/src/report/consolidated-report-generator.spec.ts
packages/shared/src/report/consolidated-report-generator.ts
packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

This adds logic to upload a build summary to the ADO extension that displays in the Extension tab. You can view a sample output here: [ADO Extension run Extension Tab output](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=30880&view=ms.vss-build-web.run-extensions-tab)
This also removes the PR Comment titles that were left over from when we switched things over to console.
Feature work
Currently the reportMarkdownConverter.convert() method is called in two separate places with the same parameters in the AdoConsoleCommentCreator. The LogResultsToConsole instance will change in a future PR, which is why I've left them separate instead of refactoring to only have it convert to markdown once.
- [n/a] Addresses an existing …

feat(ado-improvements-1): Add Build summary upload to ADO

---

docs/ado-extension-usage.md

This updates the documentation to add trailing slashes and remove double slashes for windows in siteDir and scanUrlRelativePath.  This configuration mitigates issues detailed in #1002.
Addresses issue #1002
I did test runs using `windows-latest`, `windows-2019`, and `ubuntu-latest` to verify:
[windows-latest run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=31143&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247)
[windows-2019 run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=31145&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247)
[ubuntu-latest …

feat(ADO-improvements-1): update documentation for siteDir and scanUrlRelativePath for Windows Agents

---

packages/ado-extension/src/output-hooks/ado-stdout-transformer.spec.ts
packages/ado-extension/src/output-hooks/ado-stdout-transformer.ts
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.spec.ts
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.ts

This is the final change required in #950, it adds error output for when the baseline file does not match the scan results.
It now adds an error message and also throws an exception, which will help guide users to update their baseline file when needed.
```
##[error]baselines/my-web-site.baseline(,): error :  The baseline file does not match scan results.
```
addresses #950 
Unfortunately the `task.logissue` logging command in ADO gives an extra trailing `(,)` on the error message.  This is still a big improvement over the previous error message that we had that is not actionable.  The `(,)` is supposed to be for line number/column number of the error, but that's not applicable in our case.
Also it says error twice, I looked into whether we can remove the second instance of the word …

feat(ado-improvements-1): Update baseline output on error

---

packages/ado-extension/scripts/local-overrides.json

This updates the default behavior of the `yarn start` command in the ADO extension to scan a website local to the repo rather than making an external request. This will also allow for easier testing of various scenarios, including baselining.
Output from run:
```                       
yarn run v1.22.17
$ node scripts/run-locally.js
run-locally.js is setting up input outputDir to value _accessibility-reports
run-locally.js is setting up input siteDir to value ../../dev/website-root/
run-locally.js is setting up input scanUrlRelativePath to value /
run-locally.js is setting up input maxUrls to value 100
run-locally.js is setting up input scanTimeout to value 90000
run-locally.js is setting up input singleWorker to value true
run-locally.js is setting up input failOnAccessibilityError to …
```

chore: updating default yarn start behavior to scan local website

---

packages/ado-extension/src/output-hooks/ado-stdout-transformer.spec.ts

This fixes a bug introduced in a recent PR that is causing the ADO tests to fail. See Example here: [Failed pipeline run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=31183&view=logs&j=81b7b1a0-9e2e-58a5-1601-69aaad9b82d6&t=24cd6560-9d76-5a2b-d63a-565b4fa97a0b&l=491)
Fixes known issue

fix: ADO special logging commands test

---

packages/shared/src/console-output/__snapshots__/result-console-log-builder.spec.ts.snap
packages/shared/src/console-output/result-console-log-builder.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.ts

This fixes the calculation of the rules with failures in both the markdown and console output.
Previous output below, note that 3 rules failed but the count says 6:
```
Accessibility Insights
7 failure instances
* (3) label:  Ensures every form element has a label
* (2) html-has-lang:  Ensures every HTML document has a lang attribute
* (2) image-alt:  Ensures <img> elements have alternate text or a role of none or presentation
Baseline not configured
A baseline lets you mark known failures so it's easier to identify new failures as they're introduced. See baselining docs (https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md#using-a-baseline-file) for more.
See all failures and scan details by downloading the report from run artifacts (undefined) …
```

fix: rules with failures count in markdown and console output

---

.github/dependabot.yml

This PR fixes a bit of invalid YAML syntax introduced into `dependabot.yml` in #1047. This was causing the following error when dependabot tries to parse the config file, leading it to ignore the update and keep using the configuration as of the previous commit. The error message indicating this can be found on this repo's [Insights > Dependency Graph > Dependabot page](https://github.com/microsoft/accessibility-insights-action/network/updates):
> Dependabot couldn't parse the config file at .github/dependabot.yml. The error raised was:
>
> (`<unknown>`): found character that cannot start any token while scanning for the next token at line 37 column 22
Please ensure the config file is a valid YAML file. An online YAML linter is available [here](https://jsonformatter.org/yaml-validator).
> …

chore(deps): fix invalid yaml syntax in dependabot.yml

---

docs/ado-extension-usage.md

Add the `scanTimeout` value unit (milliseconds) for clarity. I recently followed these instructions, encountering this issue of unknown units.
Updating the ADO extension usage documentation to add 'milliseconds' to the `scanTimeout` optional parameter in the pipeline configuration. 
I recently followed these instructions to set up AI in our pipelines & encountered the issue of not knowing whether the timeout value was in seconds or milliseconds. After some trial & error I discovered it was the latter. The update is to add my learnings so future readers don't encounter the same issue.

Update ado-extension-usage documentation

---

pipelines/canary-release.yaml

This fixes a syntax mistake introduced by #1093 
Feature work

fix: canary pipeline greater than syntax

---

packages/ado-extension/task.json

This introduces an advanced options group to the pipeline configuration assistant UI in ADO. It groups the `outputDir` and `chromePath` options under a collapsed by default group called `Advanced Options` that shows up at the bottom of the UI.
Here is what it looks like collapsed:
Here it is expanded:
Partially addresses #1063
We will need to add `artifactName` to the advanced options once #1085 has been merged. I'll add this in a separate commit after merging that PR into main.

feat(ado-ext-telemetry): Grouping rarely used options under Advanced Options group

---

docs/ado-extension-usage.md

The ADO extension uses Yarn to install packages before running scans on websites. Some build agents come with Yarn pre-installed, as indicated in [docs for Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software). This adds a note to indicate to users to add a step to install Yarn if it is not already included in their build agent.
It was previously unclear to users if Yarn was needed for the extension.

docs(ado-extension): add note to have yarn as a prerequisite

---

.github/dependabot.yml

`get-port` v6 and `serialize-error` v9 raised their minimum supported node versions to 12.20 (by switching to pure ESM). We still need to support node v10, so we need to ignore those updates.
We could in theory take these updates anyway and rely on webpack bundling to make it work in node v10, but I'd rather stick to a supported usage of the library since the author has committed to backporting security fixes for now anyway.
We still need to support node v10 since that's the latest we're allowed to depend on in a custom ADO task, so we need to stay on v5 until ADO enables us to update.
n/a
- [n/a] Verified code coverage for the changes made. Check coverage report at: …

chore(deps): ignore pure-ESM dependency versions in dependabot config

---

package.json
packages/shared/package.json
packages/shared/src/logger/console-logger-client.ts
packages/shared/src/logger/logger.spec.ts
packages/shared/src/logger/logger.ts
yarn.lock

Today, our logger uses `node-verror` to represent an `Error` object that can track an underlying `cause`. It does this by exposing a `cause()` method. However, since verror was written, JavaScript's TC39 group has standardized a `cause` property (not method) on the base `Error` type, which is incompatible (`cause()` vs `cause`).
This doesn't cause any issues for us today, but could in the future if, for example, we ever tracked exceptions through a library (eg, app insights) which tried to read from `cause`. It also causes errors in TypeScript 4.6.2 (see build failures in #1080), which catches the incompatible types.
This PR addresses the issue by swapping out `node-verror` for a similar library called `pony-cause` which implements an `ErrorWithCause` class comparable to `VError` but with …

chore(deps): replace verror with pony-cause to preempt future node compat issues

---

docs/ado-extension-usage.md
packages/ado-extension/src/output-hooks/ado-stdout-transformer.spec.ts
packages/ado-extension/src/output-hooks/ado-stdout-transformer.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/shared/src/console-output/__snapshots__/result-console-log-builder.spec.ts.snap
packages/shared/src/console-output/result-console-log-builder.spec.ts
packages/shared/src/console-output/result-console-log-builder.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.spec.ts
packages/shared/src/mark-down/result-markdown-builder.ts

This removes the need to have a separate publish task for the report artifacts in the azure-pipelines.yml. It is using the [special logging commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#upload-upload-an-artifact) to upload an artifact in ADO pipelines. It also updates the documentation accordingly.
I ran pipelines for Windows, Ubuntu, and Mac to ensure operability across operating systems.  I also ran a test pipeline that still had the publish step defined in the yaml file. It fails with an error stating that the artifact already exists.
- Embed Upload Pipeline runs
- Ubuntu Latest: [Pipelines - Run 20220310.2 logs (azure.com)](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_ …

feat(ado-ext-telemetry): Embed upload artifact into task

---

pipelines/canary-release.yaml

This fixes an issue introduced in #1093. The `versionOverride` parameter would default to an empty string. This worked for automated pipeline runs, but wouldn't allow manual pipeline runs to function without inputting a version number.
The ADO pipelines manual run GUI assumes it's a required field that is empty and must be filled out, even though the default is an empty string.  To address this I've set it to a string `ignore-for-patch-version-upgrade` so that you can manually run the pipeline without specifying the version number.
Here's a screenshot of the behavior, with the required field specified and the run button disabled:
bugfix
- [n/a] Verified code coverage for the …

fix: Allow manual test extension pipeline deployments without requiring version number

---

.github/pull_request_template.md

A previous feature removed the intentionally-failing "Accessibility Checks (pull_request)" check; this updates our PR template accordingly.
Makes PR template less misleading
n/a
- [nope!] (after PR created) The `Accessibility Checks (pull_request)` check should fail. All other checks should pass.

chore: remove obsolete checklist item from PR template

---

.github/workflows/ci.yml
.github/workflows/self-test.yml

We used to run a self-test of the GitHub action in our PR/CI builds, but disabled it due to #629 preventing it from working in PR builds.
However, I think it would still be valuable to run in CI builds against main, even if we can't run it with PRs yet. This restores it in a separate workflow that only triggers on pushes to main (not PRs).
Maintain ongoing validation that we haven't broken the action.
n/a

chore: create self-test workflow to run in main

---

.github/workflows/self-test.yml

This is a followup to #1110 which fixes a half-reverted change I'd been trying out to use a matrix of node versions to test with
Fixes https://github.com/microsoft/accessibility-insights-action/runs/5726695339?check_suite_focus=true
see #1110

chore: fix self-test workflow node version

---

.github/workflows/self-test.yml

The self test workflow added today in #1110 and #1111 uncovered issue #1112 when I tried to use a matrix strategy to test it across both ubuntu and windows agents. This PR disables the matrix strategy as a workaround until we fix #1112.
Unblock self-test workflow
n/a

chore: remove the os matrix from the self-test workflow

---

packages/ado-extension/package.json
packages/ado-extension/scripts/local-ado-extension-metadata.json
packages/ado-extension/scripts/run-locally.js
packages/ado-extension/src/ado-extension.ts
packages/ado-extension/src/ioc/ado-ioc-types.ts
packages/ado-extension/src/ioc/setup-ioc-container.spec.ts
packages/ado-extension/src/ioc/setup-ioc-container.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/telemetry/app-insights-telemetry-client.spec.ts
packages/ado-extension/src/telemetry/app-insights-telemetry-client.ts
packages/ado-extension/src/telemetry/telemetry-client-factory.spec.ts
packages/ado-extension/src/telemetry/telemetry-client-factory.ts
packages/shared/src/index.ts
packages/shared/src/ioc/ioc-types.ts
packages/shared/src/ioc/setup-ioc-container.spec.ts
packages/shared/src/ioc/setup-ioc-container.ts
packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts
packages/shared/src/task-config.ts
packages/shared/src/telemetry/null-telemetry-client.spec.ts
packages/shared/src/telemetry/null-telemetry-client.ts
packages/shared/src/telemetry/telemetry-client.ts
packages/shared/src/telemetry/telemetry-event.ts
yarn.lock

This PR creates an initial implementation of App Insights telemetry based on the `AdoExtensionMetadata` added in #1107. The major pieces are:
* The `shared` package contains a `TelemetryClient` interface which can track `TelemetryEvent`s. It contains a `NullTelemetryClient` which no-ops telemetry events by default. The GitHub Action does not override this behavior, so it always no-ops telemetry.
* The `shared` `scanner.ts` implementation is updated to send a single `ScanStart` event with no properties. A future PR will add a `ScanEnd` event that includes properties about number of failures/baselining state/etc
* The `ado-extension` adds a reference to the `accessibilityinsights` package and implements an `AppInsightsTelemetryClient` based on it. I have set up the client such that it omits …

feat(ado-ext-telemetry-1893588): implement App Insights telemetry entry point

---

packages/ado-extension/scripts/local-ado-extension-metadata.json
packages/ado-extension/src/ioc/setup-ioc-container.spec.ts
packages/ado-extension/src/ioc/setup-ioc-container.ts
packages/ado-extension/src/progress-reporter/telemetry/telemetry-sender.spec.ts
packages/ado-extension/src/progress-reporter/telemetry/telemetry-sender.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/src/telemetry/app-insights-telemetry-client.ts
packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/telemetry/telemetry-event.ts

This introduces a new progress reporter in the ADO Extension that collects the relevant data points and tracks the event via the `TelemetryClient`. This also changes `TelemetryEvent.properties` to accept property values of `any` type instead of strictly `string`. This makes it easier for us to pass data of all kinds. I verified that this is supported by the ApplicationInsights API based off the documentation found here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#properties
Feature work
We considered putting this logic in `scanner.ts` in the `shared` package, but it seemed like it would be the wrong abstraction as the data points needed and where to get them will likely differ between the Github Action and the ADO Extension. 
- [n/a] Addresses an …

feat(ado-ext-telemetry): add telemetry sender progress reporter

---

yarn.lock

Resolves component governance noise related to CVE-2022-24785. The issue doesn't affect our usage, but there's no reason not to update to resolve the alert.
Resolve alert noise
n/a

chore(deps): bump moment to 2.29.2 via lockfile update

---

packages/ado-extension/task.json

PR #1092 added `outputDir` and `chromePath` to a new "Advanced Options" group. PR #1122 accidentally reverted the group from `chromePath` - this PR un-reverts it and moves `chromePath` back to "Advanced Options".
Match feature spec
n/a

feat(ado-ext-telemetry): re-add chromePath to advanced options group

---

docs/ado-extension-usage.md
pipelines/ado-extension-staging-validation.yaml

This PR adds a `Migrating from version 1 to version 2` section to our ADO usage docs, and a pointer to it and the v1 docs from the top of the usage document.
Improve usability of new version
n/a

feat(ado-ext-telemetry): add a v1 to v2 migration guide for the ADO extension

---

docs/ado-extension-usage.md
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/shared/src/console-output/__snapshots__/result-console-log-builder.spec.ts.snap
packages/shared/src/console-output/result-console-log-builder.spec.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.spec.ts

Per discussion with @karanbirsingh, this PR adjusts the naming and grouping of the new inputs for automatic artifact uploading to be more consistent with the existing `outputDir` input. Previously, `outputDir` was hidden under "Advanced options" and the artifact upload inputs were named `artifactName` and `uploadResultsAsArtifact`. This PR:
* Groups the three related inputs together under a new `Output options` grouping, which appears expanded by default
* Renames `uploadResultsAsArtifact` to `uploadOutputArtifact`, to make it more apparent that it is working with the same output that `outputDir` is
* Renames `artifactName` to `outputArtifactName`, for consistency with `uploadOutputArtifact`
It adjusts all usage/tests/docs accordingly.
Feature work
Separated this out from a separate …

feat(ado-ext-telemetry): make output artifact naming/grouping more consistent with outputDir

---

docs/ado-extension-usage.md
packages/ado-extension/src/task-config/ado-task-config.spec.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/shared/src/index.ts
packages/shared/src/utils/temp-dir-creator.spec.ts
packages/shared/src/utils/temp-dir-creator.ts

This PR updates the ADO `outputDir` input to be optional without a default, instead of defaulting to `_accessibility-reports`, and to create a uniquely generated temp directory to use for `outputDir` if none is specified.
This PR intentionally does not update the GitHub Action with the same behavior because we didn't implement the embedded artifact uploading there, and it doesn't make sense to use a temp dir without the automatic artifact uploading. I did put the interesting part of the temp file generation in the `shared` package - I think if we wanted to implement it in the action in the future, it might makes sense to move the current `AdoTaskConfig.getReportOutDir` implementation into the base `TaskConfig` class as a wrapper around private-protected `getRawOutputDir` methods overriden …

feat(ado-ext-telemetry): update outputDir to write to a temp dir by default

---

.github/pull_request_template.md

Updating the PR template to encourage more information about how changes affect the ADO extension and/or GitHub action. In recent validation it was a little difficult to tell from the titles alone.
I'm equally happy with other ideas like tags, an explicit text section in this template, or individual checkboxes for impact to GH Action / ADO extension. Some of these might help with automated tooling during validation (for instance, a checkbox for each). Starting with something simple for now.
Make it easier to understand how a change affects the extension / action since they share a lot of code but the feature-set is different.
- [docs] Verified code coverage for the changes …

chore: update PR template to encourage information about how GH action & ADO extension were affected

---

yarn.lock

This PR partially addresses [this dependabot alert](https://github.com/microsoft/accessibility-insights-action/security/dependabot/16) about using a vulnerable version of "async." Where possible, it updates the dependencies we have that rely on async and bumps them to use a current, secure version of the package. For the case where this is not possible, we are choosing to resolve this dependabot alert without fixing them, as the amount of work required to make a fix is not logical for the low risk that this vulnerability poses for us.  
This dependency was updated by removing and re-adding the async@^2.0 entry of the lockfile, since our caret version, when refreshed, would bump up to a secure version of async (2.6.4). 
Keeping dependencies up-to-date.
This change leaves a few dependencies …

fix: Fixing one instance of async vulnerability

---

README.md

Dependabot's README badges broke when the old non-GitHub Dependabot migrated to GitHub. This PR removes the broken badge.
Fixes broken link/image at top of README
There isn't currently a replacement for the badge feature in the native GitHub Dependabot. https://github.com/dependabot/dependabot-core/issues/1912 tracks the request to add it, but hasn't seen activity in some time.
- [n/a] Described how this PR impacts both the ADO extension and the GitHub action

chore: remove obsolete Dependabot README badge

---

pipelines/ado-extension-staging-validation.yaml

Release 2.0.0 bumped the major version of the staging extension to 2.0.0, but our staging validation workflow is still running against version `@1`. This updates the validation template to match the updated number.
Several of the scenarios were impacted by breaking changes, and there were a few new scenarios that make sense for us to validate. This PR also updates the scenarios to be based on the new v2 functionality.
Enable release validation for 2.0.0
The syntax in the template was updated already in #1122

feat(ado-ext-telemetry): update staging validation pipeline with v2 changes

---

docs/ado-extension-usage.md
packages/ado-extension/task.json

This PR updates the labels and help text around hosting mode inputs for Classic Pipelines to be consistent with the docs/naming/error test used by YAML pipelines.
ADO-only change, no GHA impact.
Want to preempt confusion from some error message/usage docs talking about "static vs dynamic" hosting mode, when the actual option labels don't use those terms.
n/a

feat(ado-ext-telemetry: clean up labels and help text for hosting modes in classic pipelines

---

packages/ado-extension/src/progress-reporter/enforcement/__snapshots__/workflow-enforcer.spec.ts.snap
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.spec.ts
packages/ado-extension/src/progress-reporter/enforcement/workflow-enforcer.ts
packages/shared/src/index.ts
packages/shared/src/logger/recording-test-logger.spec.ts
packages/shared/src/logger/recording-test-logger.ts

The new `failOnAccessibilityError: true` default behavior interacts poorly with baseline files; it causes accessibility errors which are baselined to still fail the build, which defeats the purpose of the baseline file.
This PR updates the workflow enforcer behavior to ignore `failOnAccessibilityError` entirely if a baseline file is specified, instead.
It also improves the error output in the default case (no baseline file, default `failOnAccessibilityError` setting); previously, an accessibility error in that state would produce build log error output like this:
```
##[error]An accessibility error was found and you specified the "failOnAccessibilityError" flag.
```
This is misleading, because the common case is now going to be that the user actually didn't specify …

fix(ado-ext-telemetry): fix failOnAccessibilityError interaction with baseline files

---

packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts

The new "job summary in the ADO Extensions tab" feature uses a section header based on the filename of the markdown file we upload as the summary. Before this PR, we always used `results.md` as the filename, so we always got a section header of `results`, which didn't look quite right.
This PR updates the filename to use the following format:
* `Accessibility Insights scan summary` if the `uploadOutputArtifact` is false
* `Accessibility Insights scan summary` if we are uploading to an artifact with the default name ("accessibility-reports")
* `Accessibility Insights scan summary (artifact-name)` if we are uploading to an artifact with a non-default name (either because a user specified `outputArtifactName` themselves or because this is a rerun of a job and we've used something like …

feat(ado-ext-telemetry): improve Extensions tab summary header

---

packages/gh-action/src/task-config/gh-task-config.spec.ts
packages/gh-action/src/task-config/gh-task-config.ts
packages/shared/src/task-config.ts

In main right now, the GitHub action self test workflow (which specifies a `site-dir` and no `url`) fails with a message like this:
```
A configuration error has occurred, only one of the following inputs can be set at a time: url or site-dir
```
This happens because the input validator assumed (based on `TaskConfig` typings) that an unspecified url input would be exposed from `TaskConfig` as `undefined`. However, GitHub Actions' `getInput` return empty string rather than undefined for unspecified inputs, and `GHTaskConfig` is currently inconsistent about whether it normalizes those as `undefined` or not.
This PR updates `GHTaskConfig` to normalize unspecified parameters as `undefined` consistently. It also updates a few stray `TaskConfig` return types that should have indicated that they …

fix(gha): prevent input validator treating unspecified url input as specified

---

pipelines/package-vsix-file.yaml

We have a bash script in our release automation that echos several variables for the ADO extension (name, telemetry instrumentation key, etc). We recently changed the name of the ADO extension to a value that includes parentheses. The bash task fails: `syntax error near unexpected token `('` so this PR adds [surrounding quotes](https://tldp.org/LDP/abs/html/quotingvar.html).
No impact to GH action.
unblock release pipeline

chore: quote bash variables in ADO extension release script

---

packages/shared/src/input-validator.spec.ts
packages/shared/src/input-validator.ts

This fixes an issue with input validation that was causing the following error when `staticSiteUrlRelativePath` is not set in `dynamicSite` hosting mode:
`##[error]A configuration error has occurred, staticSiteUrlRelativePath must not be set when hostingMode is set to dynamic`
This is due to the fact that in `task.json` we have a `defaultValue` set for that input. The validator picks up the default value and assumes that the user has supplied an input.
To fix this, we have allowed the default value of `/` to be an acceptable input in the input validator. That way if there is an invalid input that we know was added by the end user it will still throw the error. This leaves the existing default value in place so as not to break existing static site setups that do not specify the input and …

fix: staticSiteUrlRelativePath validation issue

---

docs/ado-extension-usage.md

The code examples in the ADO usage docs were updated to use v2-style parameters, but we missed updating them to actually use version 2 instead of version 1 of the task. This corrects the examples.
No GHA impact.
Make usage docs match actual intended usage
n/a

docs: update ADO usage docs to use v2 instead of v1 of the task

---

pipelines/ado-extension-canary-validation.yaml
pipelines/ado-extension-prod-validation.yaml
pipelines/ado-extension-staging-validation.yaml
pipelines/ado-extension-validation-template.yaml

Today, we have a variety of staging validation scenarios, but we don't actually run them until we kick off a staging release. It would be nice to be able to validate particularly interesting/risky changes against the same scenarios in Canary without kicking off a staging release. This PR runs the same scenarios that we already run for staging releases on canary and prod release as well.
No GHA impact.
See above
n/a

chore: run validation scenarios in canary and prod as well as staging

---

yarn.lock

This PR addresses this [CG alert](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_componentGovernance/148686/alert/7200715?typeId=8236963) about using a vulnerable version of "convict" with a minor patch. This dependency was updated by removing and re-adding the convict@^6.2.1 entry of the lockfile.
Keep dependencies up-to-date and avoid vulnerabilities. 
This affects the package convict before 6.2.3.
Use for `lodash.clonedeep` and `yargs-parser` dependencies.
- [] Described how this PR impacts both the ADO extension …

fix: Update convict from 6.2.2 to 6.2.3

---

packages/gh-action/src/ioc/setup-ioc-container.ts
packages/gh-action/src/job-summary/job-summary-creator.spec.ts
packages/gh-action/src/job-summary/job-summary-creator.ts
packages/gh-action/src/task-config/gh-task-config.spec.ts
packages/gh-action/src/task-config/gh-task-config.ts

This PR adds the new Job Summary functionality to the Github Action
Here is a link to a test action run that uses the job summary, you can find it under "build summary" at the bottom of the summary tab:
https://github.com/brocktaylor7/accessibility-insights-action-test/actions/runs/2471620857
Feature work.
I spent some time looking into whether we could directly link the artifact within the job summary. Because the artifact upload happens in a subsequent step in the Github Action, the artifact doesn't yet exist when the job summary is being created and thus can't be linked.
There will be a separate PR that removes the check run and token. We may also need to look into whether we need to fail the build in that step when accessibility issues are found, as I believe the current place that …

feat(ado-gha-axe-core): Add Job Summary to GH Action

---

.gitignore
dev/README.md
packages/gh-action/deploy-scripts/deploy-to-github-test.md
packages/gh-action/deploy-scripts/validation.yml
packages/gh-action/package.json

There are a few different ways to test updates to the GitHub action. One way is to deploy the built action remotely. I am adding some information to the docs so that it's in one place. It would be nice to operationalize this into our yarn scripts, but I'm not sure I'll be able to get to that immediately - so hoping that this provides some initial info.
As an example, running the listed commands produces this repo: https://github.com/karanbirsingh/accessibility-insights-action-test-deployment which has its own action.yml. So there is no second 'client' repository required - when the repo is pushed, it immediately begins self-testing its action.
The script is inside a Markdown file which can feel like an odd choice - I didn't put it into a PowerShell script. This is because of a few …

docs: add information about test deployments to GitHub actions

---

package.json
yarn.lock

Bump node-fetch version from 2.6.1 to 2.6.7.
Keep dependencies up to date
N/a
- [n/a] Described how this PR impacts both the ADO extension and the GitHub action

chore(deps): Bump node-fetch version to 2.6.7

---

packages/ado-extension/src/output-hooks/ado-stdout-transformer.spec.ts
packages/ado-extension/src/output-hooks/ado-stdout-transformer.ts
packages/gh-action/src/output-hooks/gh-stdout-transformer.spec.ts
packages/gh-action/src/output-hooks/gh-stdout-transformer.ts
packages/shared/src/index.ts
packages/shared/src/output-hooks/stdout-preprocessor.spec.ts
packages/shared/src/output-hooks/stdout-preprocessor.ts

Currently, running the ADO extension with baselining outputs
```
To update the baseline with these changes, either rerun with --updateBaseline or copy the updated baseline file to /home/vsts/work/1/s/test.baseline
```
This PR filters out the part of the message that references --updateBaseline, so we only print
```
To update the baseline with these changes, copy the updated baseline file to /home/vsts/work/1/s/test.baseline
```
This fix affects the ADO extension, and will take effect in the Github action if baselining is enabled in the future.
Fixes #944

fix: Remove --updateBaseline info from debug logs

---

docs/gh-action-usage.md
packages/gh-action/action.yml
packages/gh-action/src/task-config/gh-task-config.ts

This PR adds `hosting-mode` to the valid list of inputs for GH Action and removes the default value for `static-site-dir`. It also changes `static-site-dir` and `static-site-url-relative-path` to be optional inputs, as they are not required in `dynamicSite` hosting mode.
Additionally updated the `gh-action-usage.md` to make the examples/suggestions more accurately reflect the new behavior and include a migration guide from v2 to v3, which specifies how to use `hosting-mode`.
During the last release validation, @lisli1 found an issue where `hosting-mode` was not recognized as a valid input, preventing GH Action from performing an accessibility test on the project.
With the default `static-site-dir`, the GH Action wasn't able to run in `dynamicSite` hosting mode, since it expects …

Fix: Adding hosting-mode to valid input list

---

packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts
packages/shared/src/telemetry/telemetry-event.ts

This PR adds a new `AuthUsed` event that tracks information about when authentication was attempted. This event is fired when a non-null value for `serviceAccountName` is found within the `scannArguments`
Feature work
This new event works as a flag and only provides information about whether an authentication attempt was made, and affects exclusively ADO Extension internal runs.

feat(ado-auth-part-2): Add telemetry for authentication events

---

docs/gh-action-usage.md

To avoid confusion since we're talking about the default being 90 seconds just before.
I wanted to bump the timeout and thought it is in seconds.
n/a
- [n/a] Described how this PR impacts both the ADO extension and the GitHub action

Clarify that the scan-timeout is in milliseconds in gh-action-usage.md

---

packages/ado-extension/package.json
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/ado-extension/task.json
yarn.lock

This makes the necessary changes to upgrade our extension to use Node16. We reduced artifact uploads to just the report and baseline if applicable due to an issue with the Node16 handler on ADO.
I followed the guide for upgrading that the build task team pointed me to, found here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode16.md
Feature work
The `azure-pipelines-task-lib` library still has the `-preview` tag. The build task team has done this intentionally to limit the number of pipelines that run on Node16 until they're able to scale up the number of available agents on Node16. The library is stable.
Several approaches were attempted with the artifact upload. I landed on manually uploading the report via logging commands, and checking for the baseline …

feat(ado-auth-part-2): Upgrade ADO Extension to use Node16

---

docs/ado-extension-overview.md
docs/ado-extension-usage.md

This updates the usage docs to use v3, and removes language about the extension being in beta.
feature work
This does not affect the GH Action

feat(ado-auth-part-2): update usage docs to use v3

---

.github/dependabot.yml
jest.config.base.js
packages/shared/package.json
packages/shared/tsconfig.json
tsconfig.base.json
yarn.lock

The shared package has pure ESM dependencies (get-port, serialize-error) which are not out-of-the-box compatible with Jest. This pull request: 
- enables `allowJs` in the tsconfig which will allow ts-jest to transform these modules. 
- sets `include` to the shared tsconfig to prevent extraneous js files from changing the compile file directory.
- removes the dependabot version pins for the dependencies and update them to their latest versions.
Addresses #1000
An alternative approach is to use babel-jest to transform the ESM dependencies. This would require two new dependencies to maintain and making sure regenerator-runtime runs before Jest starts up. One benefit with this solution is that it doesn't modify the tsconfig. [Example …

chore: Enable allowJs to support pure ESM with Jest

---

.github/dependabot.yml
packages/shared/package.json
yarn.lock

Now that the ADO extension supports Node 16, we can remove the dependabot version pin on marked-terminal and update it to the latest version.
Keep packages up-to-date.

chore: Remove marked-terminal version pin

---

docs/ado-extension-usage.md
docs/ado-extension/migrating-from-v1-to-v2.md

This improves documentation that comes along with v3 updates with the following updates:
- Moves v1 to v2 migration guide to a new file and links to it
- Clarification of required scenarios in order to use the extension (e.g. serve site in pipeline, point to html file, or point to preproduction site)
- Updates baseline section to reflect auto-uploading of baseline file artifact
- Updates a couple references from v2 to v3
Improving documentation
This has no impact on the GH action.

chore: Update docs to better reflect v3 changes

---

packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/gh-action/src/job-summary/job-summary-creator.spec.ts
packages/gh-action/src/job-summary/job-summary-creator.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/report-markdown-convertor.spec.ts
packages/shared/src/mark-down/report-markdown-convertor.ts
packages/shared/src/mark-down/result-markdown-builder.spec.ts
packages/shared/src/mark-down/result-markdown-builder.ts

This changes the emojis included in markdown output to be unicode emojis on ADO.
Here is a test build output using the Unicode emojis in ADO: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=36820&view=ms.vss-build-web.run-extensions-tab
addresses issue #1263 
I considered just changing to unicode emojis for both Github and ADO, but I decided to introduce a new `executionEnvironment` variable that allows us to output different emojis for ADO and GH. This will allow us to use the markdown emojis on GH once baselining is enabled on the action.
Currently this has no impact on the GH action, but does impact markdown output in the future if baselining is enabled.

fix: Update emojis to use unicode for ADO

---

pipelines/build.yaml

Update the ubuntu version to latest to move off 18.04. I noticed the following warning:
> ##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
Keep pipeline environments up to date.

chore: update ubuntu version to 20.04

---

packages/shared/package.json
yarn.lock

Upgrade the `accessibility-insights-scan` package to 1.4.0 to enable two new checks in both the GitHub Action and the ADO extension.
Feature work

chore(deps): bump accessibility-insights-scan from 1.3.0 to 1.4.0

---

packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

This fixes an issue causing misleading error messages to appear when configuration issues or other errors cause the accessibility-insights-scan package to return an error.
When an error is surfaced from the scan package it returns it in `CombinedScanResults.errors` with empty `CombinedReportParameters`. We were previously not handling this scenario, so when the next step of the code was attempting to get the `baseUrl` from the `CombinedReportParameters`, it would fail and throw an ambiguous error message about the `baseUrl` that had nothing to do with the actual error.
This adds a check for the `CombinedScanResults.errors` array to ensure it's empty, and if it isn't it surfaces any errors returned in the array and fails the run.
This issue was occuring in the `shared` package that is …

fix: Surface error messages properly from the scanner

---

package.json
yarn.lock

This pull request will add a yarn resolution for [mockery](https://github.com/mfncooper/mockery), which is used by azure-pipelines-task-lib.
Resolve CG work item.

chore: Set yarn resolution for mockery

---

pipelines/build.yaml

There are reliability issues with the notice file generator API which can require you to rerun failed jobs. After reaching out to the support team for this service, they recommended setting a retry on the task: https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-195-update#automatic-retries-for-a-task. This PR will ask the task to retry 3 times before failing. 
Improve contributor experience.

chore: Add `retryCountOnTaskFailure` to notice task

---

packages/ado-extension/task.json

Adds an empty option for authType in the ADO extension's task.json. This will fix an issue where classic pipeline users saw an invalid option error for the field.
This change does not impact the GitHub action.
Address issue #1357 
I pushed this branch to a staging task and was able to verify the expected behavior.
In the screenshot below. I am able to bypass the Authentication type error as the dropdown automatically selects the empty value. The YAML shows that `authType` is not set. I am able to save and queue the pipeline:
In the screenshot below, I am able to add an auth type and (fake) service account name and password. The YAML shows that `authType`, `serviceAccountName`, and `serviceAccountPassword` are set as expected.  I am able to save and queue the pipeline:
- [n/a] Added …

fix: Add empty option for authType

---

docs/ado-extension-usage.md
docs/gh-action-usage.md
packages/shared/src/scanner/scanner.ts

The browser resolution set by ai-scan is 800x600, this pull request updates the set `scanResultData.browserResolution` to match. This value is printed at the bottom of reports. This pull request will also add a bullet point to each usage document to specify the viewport size.
Is there a way to pull this from the ai-scan to prevent future mismatches? It doesn't look likely. This is something we should consider if we decide to create viewport inputs.

fix: browser resolution set by ai-scan is 800x600

---

packages/ado-extension/src/progress-reporter/telemetry/telemetry-sender.spec.ts
packages/ado-extension/src/progress-reporter/telemetry/telemetry-sender.ts

This PR adds a new telemetry entry point to count the number of issues found in a baseline file.
This will help us understand if users are fixing issues over baseline, introducing new ones, or updating baseline files.
This change will affect exclusively ADO Extension side.
Right now we don't have a sure way of knowing what was the initial state of a baseline file, this PR will help us understand how many issues were found in the baseline file and will bright us more insights to determine if baseline was modified over a period of time.
I tested locally using dev telemetry and everything looks right, the new entry point now shows in the telemetry reports.
(Image showing the number of baseline failures in test results)

chore: Adding new telemetry entry point for baseline issues count

---

packages/ado-extension/task.json

Based on user feedback and suggestions gathered from action triage, this PR will improve the classic pipeline flow by updating ADO labels and:
- Use sentence case for all labels which is consistent with ADO pipelines
- Add documentation links where possible
- Rework hosting mode values to be "URL" or "Static site"
- Rework "URL relative path" to "base URL"
- Add a prefix to conditional inputs labels (such as `Authentication`) to help group conditional values
- A few additional small copyedits
- Use markdown formatting where possible
You can preview the changes in this pull request from this pipeline: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=109
This PR only impacts the ADO …

chore: Update ADO labels to improve classic pipeline flow

---

docs/ado-extension-usage.md
docs/gh-action-usage.md
packages/shared/package.json
packages/shared/src/scanner/scanner.ts
yarn.lock

This consumes the latest scan package that includes a fix for the viewport size. This also changes the report to report the new 1920x1080 viewport size that the scan package now defaults to.
Fixes bugs and prepares us for release.
This affects both the GH Action and ADO Extension equally, and documentation is updated for both

chore: update scan package and reported viewport size

---

package.json
tools/get-change-log-for-release.js
yarn.lock

This adds a script to generate a changelog during release. This copies from the optional script we have for Accessibility Insights for Web releases.
It auto-generates the tester, verified, dev, commit, pr, change description, group, version, and date columns for all the changes between the current release and the previous.
To run it, in the root of the action repo you run the following command, for this example I'm using the previous two release tags:
`node ./tools/get-change-log-for-release.js --from v3.1.0 --to v3.1.1 `
This is the resulting file from that command:
[change-log.v3.1.0-v3.1.1.csv](https://github.com/microsoft/accessibility-insights-action/files/9933118/change-log.v3.1.0-v3.1.1.csv)
Once the table is generated and filtered, it looks like this (an example of what the …

chore: add release change log generation tool

---

packages/ado-extension/src/ado-extension-test.spec.ts
packages/ado-extension/src/ado-extension.ts
packages/ado-extension/src/index.ts
packages/shared/package.json
yarn.lock

This adds a `process.exit()` at the end of execution to ensure the task doesn't hang.
Bug fix in preparation for release
This is a bug that we had discovered during release validation that was causing the process to hang.  We discovered that the `accessibility-insights-scan` package was having the same thing happening so we fixed it and released that package upstream.  Perplexingly, the issue wasn't resolved by the upstream fix.
I have implemented a similar fix here by adding a `process.exit()` at the end of execution. I had initially considered adding it to a `finally` block within `packages/ado-extension/src/ado-extension.ts`, but it felt wrong to end the process one level down from the top-level call in `index.ts`. 
When I initially put the `process.exit()` in `index.ts`, it was …

fix: add process.exit to fix process hanging at the end of execution

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/combine-dependabot-prs.yml
.github/workflows/self-test.yml

This pull request updates actions as recommended and configures Dependabot to keep github-actions updated for us.
There are several github-actions that are emitting the following warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/checkout
For the updated actions, each saw an update to Node 16 in v3 and no other notable breaking changes. The list below contains the changelogs or releases for the updated actions:
- https://github.com/actions/checkout/blob/main/CHANGELOG.md#v300 
- https://github.com/actions/setup-node/releases/tag/v3.0.0
- …

chore: configure dependabot to check for action dependency updates

---

packages/ado-extension/task.json

This PR will add back the `defaultValue` for `staticSiteUrlRelativePath` which had been removed in #1371.
While working on release validation, I noticed that the static site tests were failing when they should not with:
```
##[error][Exception]ErrorWithCause: An error occurred while scanning website page: undefined
at Logger.trackExceptionAny (/home/vsts/work/_tasks/accessibility-insights_aebf5565-d905-5999-8faf-a44d4db6c0fa/3.0.5/index.js:189373:29)
at Scanner.logAndTrackScanningException (/home/vsts/work/_tasks/accessibility-insights_aebf5565-d905-5999-8faf-a44d4db6c0fa/3.0.5/index.js:190604:21)
at Scanner.<anonymous> (/home/vsts/work/_tasks/accessibility-insights_aebf5565-d905-5999-8faf-a44d4db6c0fa/3.0.5/index.js:190568:22)
at Generator.next (<anonymous>)
at fulfilled …
```

fix: Add back defaultValue for staticSiteUrlRelativePath

---

packages/ado-extension/e2e/ado-extension.test.ts

This PR makes a small change to the expected output. The branch got behind the scan package which had the viewport fix, which I suspect caused the change in number of pass and not applicable.
This PR only impacts the extension.
Fix broken tests on main.

fix: Fix expected output for e2e test

---

.vscode/extensions.json
.vscode/settings.json

This pull request will update the vscode files to:
- set `editor.defaultFormatter` this seems to help make prettier format on save
- set `psi-header` configuration to automatically add copyright on new files
-  add `extensions.json` with recommended extensions for this workspace
Synchronize vscode settings across projects and improve contributor efficiency 

chore: update vscode settings to format on save and add copyright on new files

---

jest.config.base.js
packages/ado-extension/e2e/ado-extension.test.ts
packages/ado-extension/e2e/mock-test-runner.js
packages/ado-extension/e2e/mock-test.ts
packages/ado-extension/package.json
yarn.lock

This takes the existing E2E infrastructure and adds the ability to pass in varying inputs. It also adjusts the jest config and package.json to run the relevant tests when calling from yarn.
I added an additional E2E test to demonstrate the ability to pass in different inputs with the new setup.
It also updates the yarn.lock file because that didn't happen last week, apparently. 
Feature work
More E2E tests to come in future PRs.
This does not affect the GH Action.

feat(docs-tests-telemetry): add ability to pass inputs into e2e mock test runner

---

dev/website-baselines/e2e-baseline-1.baseline
dev/website-baselines/e2e-baseline-2.baseline
packages/ado-extension/e2e/ado-extension.test.ts

This adds various E2E test scenarios that will run on PR. The scenarios added are:
The ADO Extension:
- Limits the number of pages crawled and scanned when `MaxUrls` input is set
- Only scans the `inputUrls` when `maxUrls` input matches the number of `inputUrls`
- Scans pages that are passed in as `inputUrls`
- Should fail if both `url` and `staticSiteDir` are defined
- Should find no additional failures when a baseline is properly configured
- Should find additional failures when the baseline does not cover all failures
- Should fail scan and generate a baseline file if `baselineFile` input is specified and the file does not exist
Feature work
This does not impact the GH Action

feat(docs-tests-telemetry): Add E2E test scenarios

---

packages/ado-extension/e2e/ado-extension.test.ts

I noticed that the e2e tests on the ADO pipeline are failing. I believe this is because when we log the stdout from the e2e tests, the errors collected from the tests are triggering failures in the pipeline. This pull request will add a small function that will replace the ADO logging commands with `##[error]` which will format as an error in the pipeline, but not fail the pipeline.
Example failing build: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=39572&view=logs&j=81b7b1a0-9e2e-58a5-1601-69aaad9b82d6&t=5cf72e78-07c0-5125-1262-b1e05b2475fe
Unblock pipeline.
For visibility, it would be ideal to keep printing the stdout with each test, but I'm not sure how to prevent the collected errors from pulling through. I tried:
- …

fix: prevent e2e stdout from triggering build failure on Azure pipeline

---

pipelines/ado-extension-canary-validation.yaml
pipelines/ado-extension-prod-validation.yaml
pipelines/ado-extension-staging-validation.yaml
pipelines/ado-extension-validation-template.yaml

This adds auth testing to the canary pipeline. It uses a variable group to supply the service account credentials to the pipeline.
Here is a [run of the new canary pipeline](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=40041&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=68db983b-a3f3-5e3d-e1bc-86012b574de0)
Feature work
Both the canary and staging pipelines were setup to run on PR, but were running against the canary and staging extensions respectively. This doesn't make sense as it doesn't test the actual changes in the PR, it only tests the already published staging or canary extension. Due to this I've removed the PR trigger but left the resources trigger that will run the pipeline after the staging and canary …

feat(docs-tests-telemetry): Add auth testing to canary

---

packages/ado-extension/src/task-config/ado-task-config.ts
packages/shared/src/console-output/__snapshots__/result-console-log-builder.spec.ts.snap
packages/shared/src/console-output/result-console-log-builder.ts
packages/shared/src/input-validator.spec.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/result-markdown-builder.ts

Updates a few hardcoded documentation links with aka.ms links. This will not only allow us to direct users to the new documentation page, but also allow us to update the target in the future without needing to release the extension.
Keep documentation references up-to-date
- ~~[ ] Described how this PR impacts both the ADO extension and the GitHub action~~

fix: Update links to extension docs with aka.ms links

---

packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/shared/src/mark-down/__snapshots__/result-markdown-builder.spec.ts.snap
packages/shared/src/mark-down/report-markdown-convertor.spec.ts
packages/shared/src/mark-down/report-markdown-convertor.ts
packages/shared/src/mark-down/result-markdown-builder.spec.ts
packages/shared/src/mark-down/result-markdown-builder.ts

This pull request removes action specific code from the shared package:
- Remove execution environment from markdown reporters
Feature work
We considered keeping the execution environment, but it's only used for the logic of switching the emoji. Since it would be fairly quick to add back, we decided to remove the execution environment for now.
- [n/a] Described how this PR impacts both the ADO extension and the GitHub action

feat(decommission-gh-action): Remove action specific code from shared package

---

pipelines/build.yaml

This pull request will remove the GitHub action from the build pipeline.
From what I understand, the gh-action was placed in an artifact at `drop/packages/gh-action/`, while the extension lives in an artifact at `ado-extension-drop/pkg/`. This PR will remove the `drop/` directory at the root since that appears to be for the action only. The REALEASE_COMMIT.md was saved in `ado-extension-drop/drop`, but I moved that up a directory into `ado-extension-drop` to simplify the directory structure.
- Example of artifact before this PR: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=40217&view=artifacts&pathAsName=false&type=publishedArtifacts
- Example of artifact with this PR: …

feat(decommission-gh-action): Remove gh-action from build pipeline

---

packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts
packages/shared/src/task-config.ts
packages/shared/src/telemetry/telemetry-event.ts

This adds telemetry tracking of usage of the `failOnAccessibilityError` input.
To allow for visibility into compliance of failing pull requests if accessibility errors are found and no baseline is in place. If `failOnAccessibilityError` is set to `true`, the extension will always return as successful even if there are errors, rendering the extension mostly useless.

feat(telemetry-and-inputs): add failOnAccessibilityError telemetry

---

docs/ado-extension-inputs.md
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.spec.ts
packages/ado-extension/src/progress-reporter/console/ado-console-comment-creator.ts
packages/ado-extension/src/task-config/ado-task-config.ts
packages/ado-extension/task.json
packages/shared/src/scanner/crawl-argument-handler.spec.ts
packages/shared/src/scanner/crawl-argument-handler.ts
packages/shared/src/task-config.ts

This adds the snapshot input available in the accessibility-insights-scan package to the ADO Extension. The snapshot input takes a snapshot of every page scanned and uploads it to a separate artifact folder using the existing artifact name and appending `-snapshots`.
Here is an [example run from my test extension](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=41619&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247)
Here is a [direct link to the artifacts for that run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=41619&view=artifacts&pathAsName=false&type=publishedArtifacts)
Feature work, this will allow users to see …

feat(telemetry-and-inputs): add snapshot input and snapshot artifact upload

---

packages/ado-extension/src/task-config/ado-task-config.ts
packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

This adds staticSiteDir to the list of inputs telemetry that we're collecting.  
Rather than collect the entire value for `staticSiteDir`, this records a `staticSiteDirSet` boolean value, as we don't need to know the path, only if they're using the input or not.
We want to track how often the static site option is being used with the end goal of removing it in the future if it is not being used much. Removing this input in the future would allow us to also remove the `dynamicSite` and `staticSite` options that tend to cause confusion for many teams onboarding. It also wouldn't prevent people from scanning static sites, they would just need to serve those sites in the pipeline on their own.

feat(telemetry-and-inputs): add staticSiteDir telemetry

---

packages/ado-extension/e2e/ado-extension.test.ts

This pull request will clip the e2e scan summary snapshot slightly to make sure the snapshot is consistent in every build environment.
In #1535 we added an e2e snapshot test to capture the scan summary. When the pull request merged and triggered the build pipeline, the new test failed. This is because the build pipeline was able to upload and capture the artifact URL, which changed the snapshot. The added line to the snapshot: "To see all failures and scan details, download the accessibility report (link)".
Make tests passing.
- I don't think there's a way to mock the artifact URL. While it's possible to register mocks with the azure-pipelines-task-lib, since the TaskMockRunner is executing on compiled code, I wasn't able to find a way to register the mock successfully.
- I considered …

fix: Rework e2e scan summary snapshot

---

pipelines/package-vsix-file.yaml

This adds an installation step for a package that was missing in the release pipeline VM, causing the ESRP signing to fail as demonstrated in [this pipeline run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=42108&view=logs&j=396ea3d1-819f-56b8-6471-9a0868242726&t=7ac2f2c6-f908-505b-7eb0-4caa111ca6d9).
I dug around and found various people working around this issue by installing the missing .NET package using the `UseDotNet@2` task. To verify that it would work as expected, I pushed this branch and ran the pipeline using the yaml file from this branch. It succeeded, as you can see in [this successful pipeline run](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildI …

fix: add .net core sdk 2.1.x installation to package-vsix-file.yml

---

pipelines/ado-extension-validation-template.yaml

This pull request adds NodeTool to make sure the validation pipeline use Node 16.x. I noticed the canary validation pipelines started failing yesterday with a Node version error; ubuntu-latest appears to be shipping with Node v18. 
Fix validation pipelines.

fix: Add NodeTool to validation pipelines

---

packages/ado-extension/task.json

This points the top-level  `helpMarkdown` in the `task.json` file to the new FAQ link.  This snippet is displayed at the top of the task whenever it is run.
Here is a run with my test extension displaying the new behavior: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=42652&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247
This allows us to point users to a single place for both configuration and troubleshooting questions.
We'll also be updating the eng.ms documentation to link back to setup documentation. 

feat(faq-update): point helpMarkdown to new FAQ link

---

yarn.lock

Pin to a higher version of http-cache-semantics transitive dependency to ensure we get security fixes (see https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_workitems/edit/312)
Keep dependencies up to date

chore: Bump http-cache-semantics transitive dependency

---

package.json
yarn.lock

This PR cleans up the repo's use of yarn resolutions:
* Removes a few obsolete resolutions
* Updates remaining resolutions to take advantage of yarn v3's versioned specifiers
In practice, the actual delta of packages we resolve to is:
* `hosted-git-info` is downgraded, but not past the version boundary containing security fixes we want to maintain (3.0.8). This is intentional, to avoid accidentally picking up breaking changes unnecessarily
* one `lru-cache` version is collapsed away (as a follow-on effect of the `hosted-git-info` downgrade)
* `node-fetch` is upgraded slightly (`2.6.7` to `2.6.9`) in one path that wasn't intended to be impacted by its resolution
* Removing obsolete resolutions removes some existing tech debt
* Using versioned specifiers avoids issues where we accidentally …

chore: clean up yarn resolutions using versioned specifiers

---

pipelines/build.yaml

As I was investigating the run times before and after 1ES PT migration for the CI template, I noticed that the yarn install step was taking 3+ minutes due to a node-gyp issue. Adding back Node 16 to the pipeline resolves the node-gyp error and makes the yarn install steps run significantly faster.
Improvements to https://github.com/microsoft/accessibility-insights-action/pull/1610, https://dev.azure.com/mseng/1ES/_workitems/edit/2033962

feat(onboard-1es-pt): Add back NodeTool tasks back to CI pipeline

---

packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

This PR adds a `{ recursive: true }` option to the point where we create the `outputDir`, such that it will no longer be an error to specify an outputDir with an ancestor that doesn't exist yet.
Addresses #1609 
n/a

fix: avoid error when outputDir is contained in a non-existent directory

---

package.json
yarn.lock

Removed the `yaml` dependency and updated to a later version of the `cosmiconfig` package that uses `js-yaml` instead
The older version of `yaml` had a security vulnerability. Since the dependency was introduced by `cosmiconfig`, opted to update this package, which switched to the `js-yaml` parser
- [N/A] Addresses an existing issue: Fixes #0000
- [N/A] Added relevant unit test for your changes. (`yarn test`)

fix: removing yaml dependency

---

packages/shared/src/scanner/scanner.spec.ts
packages/shared/src/scanner/scanner.ts

This PR improves the log message we emit when the task is using a default (unset) `chromePath`. Previously, the log message said this would result in using the "system default", which is misleading; what we actually use (both in practice and as-documented) in that case is the version of Chromium bundled with Puppeteer.
See second bullet point in https://github.com/microsoft/accessibility-insights-service/issues/2426#issuecomment-1528125055
https://github.com/microsoft/accessibility-insights-service/issues/2426

fix: improve accuracy of log message default `chromePath` behavior

---

.github/dependabot.yml

Increase dependabot PR limit from the default of 5. We've seen cases where our updates get blocked behind dependabot PR's that contain breaking changes. Since we're scheduled to run dependabot once per day, we end up accumulating updates without realizing it.
Updates shouldn't hide in the dependabot queue.
- [n/a] Addresses an existing issue: Fixes 

chore: Increase dependabot PR limit

---

package.json
yarn.lock

Force resolution of the `tough-cookie` package to 4.1.3.
Address [CVE-2023-26136](https://nvd.nist.gov/vuln/detail/CVE-2023-26136)
- [n/a] Addresses an existing issue

chore: Force resolution to tough-cookie 4.1.3

---

packages/ado-extension/e2e/ado-extension.test.ts

Add e2e scenarios to pin existing crawling behavior. The gaps were noticed when considering moving to ai-scan 2.x
Detect future crawling changes
This adds 2 tests with identical checks as an existing test. I thought about using the `it.each` construct for the existing test, but it seemed better to have 3 simple tests than one that is harder to read
- [n/a] Addresses an existing issue:

chore: Pin e2e scenarios that were previously omitted

---

packages/ado-extension/e2e/ado-extension.test.ts
packages/ado-extension/e2e/mock-test.ts
packages/shared/package.json
packages/shared/src/console-output/__custom-snapshots__/axe-descriptions.snap.md
packages/shared/src/mark-down/__custom-snapshots__/axe-descriptions.snap.md
yarn.lock

This PR updates to axe-core 4.7.2 and ai-scan 2.3.1. The tests have all been updated, including increasing the timeout of an e2e test that is slightly slower due to additional redirect overheads that exist in this scenario.
Feature work
- [n/a] Addresses an existing issue

feat: Upgrade to axe-core 4.7.2

---

docs/ado-extension-inputs.md

#1815 highlighted a misunderstanding of the different cases where the ADO extension will report an error. This adds more explanation to the documentation of the inputs to try to address this misunderstanding.
Address #1815, improve docs

fix: Clarify failure modes

---

packages/ado-extension/e2e/__snapshots__/ado-extension.test.ts.snap
packages/ado-extension/e2e/ado-extension.test.ts
packages/shared/src/logger/__snapshots__/recording-test-logger.spec.ts.snap
packages/shared/src/logger/recording-test-logger.spec.ts
packages/shared/src/progress-reporter/__snapshots__/all-progress-reporter.spec.ts.snap
packages/shared/src/progress-reporter/all-progress-reporter.spec.ts
packages/shared/src/utils/__snapshots__/aggregate-error.spec.ts.snap
packages/shared/src/utils/aggregate-error.spec.ts

Due to https://github.com/jestjs/jest/issues/14305, our inline snapshots are causing problems when using `yarn test -u`. We discussed this internally and decided that the simplest approach was to convert the inline snapshots to traditional snapshots. For most cases, this was just removing "Inline" from the method name and removing the string that provided the snapshot. A small number of test cases were checking multiple inline snapshots in the same test, so the approach there was to build an array of the things that were previously checked individually, then having a single snapshot for the test case.
I ran `yarn test -u` and `yarn format:fix` after making all of the changes, just to make sure that we're ready for future changes.
It will probably be easiest to review this one commit at a …

Chore: Remove inline snapshots

---

pipelines/canary-release.yaml

This change adds signing of the Canary release of the ADO extension. While signing is required only for the Production release, signing the Canary release provides with an early warning of potential signing problems (like the one that we had earlier this year when our secret expired without our realizing it).
Signing takes about 2 minutes, so the release pipeline total time will go from about 2 minutes to about 4 minutes. None of our processes rely on the pipeline speed, so this seems like an acceptable change.
Test build using this change: https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=47432&view=results
Avoid surprises when we need a production release
I considered making the signing variable default to false for Canary, …

chore: Sign Canary build in validation pipeline

---

pipelines/ado-extension-validation-template.yaml

The current validation steps are 
Make it easier to determine the successful and failing cases. The cases are called out as succeeding or failing and are separately numbered to make it easier to add new cases to each in the future.
The `success-3` case is currently failing due to #1713, so we will need to update the template once that is fixed. The final result can be found at https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=47465&view=results
The commits here are intentionally small, which might help simplify the review process
- [n/a] Addresses an existing issue: 
- [n/a] Verified code coverage for the changes made. Check coverage report at: …

chore: Reorder validation steps in pipeline template

---

docs/ado-extension-inputs.md
packages/ado-extension/task.json

In #1820, manual edits were made directly into inputs.md file. This is a tool-generated file, so manual edits get lost when the file is next generated. This PR attempts to restate the core messaging of #1820, but to do it in a way that will persist when the docs are regenerated.
Follow original intent that was previously overlooked, fix `yarn precheckin`

chore: Use auto-generated docs file

---

pipelines/ado-extension-canary-validation.yaml
pipelines/ado-extension-validation-template.yaml

On August 30th, our Canary releases were (probably unintentionally) bumped from 1.X to 3.X. The validation pipeline didn't update, so our Canary validations have been running the wrong version for several weeks. This change gets us back in sync with the Canary releases and increases the scanning timeout since the new crawler is a little slower than the old one was.
Also, we're not in a shippable state because of a problem with telemetry initialization that we'll fix separately.
Canary pipeline needs to be reliable
There are 3 things this doesn't address and that we might want to do in the future:
- Should we restore Canary as v1.X? This will require cleaning up the existing 3.X versions, resetting the canary prototype, and maybe adding a guard against another unintended change of the …

fix: Run current canary release

---

.github/dependabot.yml

* Dependabot for our repos is scheduled to run at fairly different times that are inconvenient for some geographies. This PR moves this repo's dependabot time to 08:30 UTC (14:00 IST, 01:30 PDT, 00:30 PST).
* Web-based projects have many dependencies, and a low Dependabot PR limit causes us to need to run Dependabot manually multiple times to update all dependencies. This PR increases the limit.
Part of [Feature 2083093](https://mseng.visualstudio.com/1ES/_queries/edit/2083093) (internal access required to view).

feat(oncall-vendor-transition): Increase Dependabot limit and move scheduled runs to 08:30 UTC

---

.github/dependabot.yml
packages/ado-extension/package.json
yarn.lock

Dependabot updated the applicationinsights version while our Canary validation pipeline was running the wrong version. The Canary pipeline is currently failing during telemetry initialization, so the simplest step is to roll back so we're again in a working state. This includes a fix to prevent dependabot from suggesting updates before we're ready
We should always be in a shippable state
We could fix the telemetry initialization, but we don't know how hard that will be. This is the quick fix until we're ready for the "real" fix

fix: Fix telemetry initialization error by rolling back

---

pipelines/canary-release.yaml

When running in the Canary validation pipeline, the ADO extension is throwing an error that it can't locate `applicationinsights.json` in the `node_modules` folder. I've been able to prove that `applicationinsights,json` was present in Canary release 3.5.2 and earlier, but is absent in Canary release 3.5.3 and newer. There were 2 changes between the 2 releases: #1804 (bump the `@types/lodash` version) and #1823 (sign the Canary package). Of the two changes, it seems much more likely that signing the package was the cause of the change. It's also the simpler change to revert, so we'll give it a try.
Hopefully fix issue in Canary validation pipeline
If this fixes the problem, we'll also want to revert #1866, which was the assumed (but later disproven) source of the Canary pipeline problem. …

chore: Revert #1823

---

pipelines/canary-release.yaml

Canary signing has flip-flopped. In #1823, it apparently broke our Canary validation pipeline. #1871 reverted it, but the pipeline was actually working before #1871 merged, suggesting that something else was causing the problem. So this is setting the signing flag back to true since we want that behavior and the empirical data suggests that we can.
Signing the Canary build is a good early warning of expired secrets

chore: Restore canary signing

---

pipelines/ado-extension-validation-template.yaml

Our validation pipeline is not very good at surfacing customer-impacting failures. It intentionally contains "should succeed" and "should fail" test cases, but failures from the "should fail" cases could mean "we completed the analysis and found accessibility errors" or "we failed to complete the analysis". ADO returns both cases as "partially successful", and the differences are only apparent by drilling down into the logs. This is why the puppeteer failure went unnoticed for so long.
This PR improves validation usefulness by splitting the validation into 2 jobs--one that runs the tests, and one that validates the artifacts generated while running those tests. If any of the test cases fail to run, it will cause the set of artifacts to change, and the validation job will fail. If the …

Chore: Make validation pipelines more sensitive and meaningful

---

pipelines/ado-extension-validation-template.yaml

When #1874 rearranged the validation tests, an unnecessary condition was left in place. it's unnecessary because the run should fail if either of the 2 previous test steps fail. Leaving the condition in place doesn't impact the overall result (thanks to the validation job), but it's both slower and inconsistent with the comment on lines 50 and 51.
Validation run is at https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=48628&view=results
Avoid maintaining unnecessary stuff

chore: Remove unneeded condition

---

yarn.lock

After merging PR #2010, dependabot shown below alerts for vulnerable versions. These 2 packages are added as dependency of test website for e2e testing. Upgraded both packages to stable version as recommended by dependabot.
Dependabot Alerts which fixed:
https://github.com/microsoft/accessibility-insights-action/security/dependabot/59
https://github.com/microsoft/accessibility-insights-action/security/dependabot/58

chore(deps-dev): Upgrade postcss and nth-check packages

---

.github/dependabot.yml

react-router-dom is used for test website for testing Urls with hash fragments.
The feature hashType="noslash" used in test website is not supported from v6. Please refer https://github.com/remix-run/react-router/issues/11076 for more details. As per this, this feature is not going to be supported in future version so we have to stick with v5 only
Also closed out dependabot PR https://github.com/microsoft/accessibility-insights-action/pull/2024

chore(deps): added react-router-dom to ignore list of dependabot updates

---

pipelines/Create ESRP service connection.yml
pipelines/ado-extension-canary-validation.yaml
pipelines/ado-extension-prod-validation.yaml
pipelines/ado-extension-staging-validation.yaml
pipelines/canary-release.yaml
pipelines/package-vsix-file.yaml
pipelines/prod-release.yaml

Created new variable groups, service connections and environments in mseng ADO. As this is common ADO for different team so appended a11y-insights in all the names to distinguish them for our team.

fix: updated variable group and service connection names in yaml pipelines

---

pipelines/prod-release.yaml

Updated git hub service connection name for creating release tag from mseng ADO.

fix: update github service connection for create release tag in yaml pipeline

---

pipelines/ado-extension-validation-template.yaml

Added the new task in validation pipeline to validate the new parameter "keepUrlFragment" functionality in pipeline
[Feature 2114928](https://dev.azure.com/mseng/1ES/_workitems/edit/2114928): ADO Extension should be able to crawl hash-routing SPA apps

feat(crawl-hash-urls): Updated ADO task validation pipeline for new parameter

---

yarn.lock

Bumps [ip](https://github.com/indutny/node-ip) from 1.1.9 to 2.0.1.
https://github.com/microsoft/accessibility-insights-action/security/dependabot/56
There is a dependabot security alert for ip. But dependabot is unable to create a PR for upgraded version.
Creating Manual PR for that.
- [na] Addresses an existing issue: Fixes #0000
- [na] Added relevant unit test for your changes. (`yarn test`)
- [na] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`

chore(deps): Bump ip from 1.1.9 to 2.0.1

---

pipelines/ado-extension-validation-template.yaml

Added the new task in validation pipeline to validate the new parameter "npmRegistryUrl" functionality in pipeline
[Feature 2207295](https://dev.azure.com/mseng/1ES/_workitems/edit/2207295): Enable option to use private npm registry Url in a11y ado extension
- [na] Addresses an existing issue: Fixes #0000
- [na] Added relevant unit test for your changes. (`yarn test`)
- [na] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`

feat(private npm registry): Updated ADO task validation pipeline for private registry parameter

---

package.json
packages/shared/package.json
yarn.lock

Upgrade express from 4.19.2 to 4.20.0 to fix the vulnerability.
Upgrade serve-static from 1.15.0 to 1.16.0 to fix the vulnerability.
Upgrade send from 0.18.0 to 0.19.0 to fix the vulnerability.
Upgrade body-parser from 1.20.2 to 1.20.3 to fix the vulnerability.
Upgrade path-to-regexp from 0.1.7 to 0.1.10 to fix the vulnerability.
Upgrade path-to-regexp from 1.8.0 to 1.9.0 to fix the vulnerability.
[CG Work Items](https://dev.azure.com/mseng/1ES/_queries/query/894c54da-1edd-4c5c-ae4d-38903314430c/)

chore: Upgraded package versions for CGAlerts

---

.github/workflows/ci.yml
pipelines/build.yaml

Disable the code coverage command in the CI workflow. As Codecov package is deprecated.
Commented out the codecov command from build yml files

fix: skip codecov publish report step in ci pipeline

---

packages/ado-extension/src/install-runtime-dependencies.ts
packages/shared/package.json
yarn.lock

This PR adjust the logic to set yarn config before installing runtime dependencies. It filters out environment variables starting with yarn_. This is to make Yarn commands for ado extension independent of any environment setting and if environment variable contains invalid/unrecognized variable starting with yarn_  than it throughs error. For example, environment YARN_MIN_VERSION (This is no valid config in yarn 3) will give below error:
_Unrecognized or legacy configuration settings found: minVersion - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)_
Also it updates accessibility insights scan package to fix the issue #2182.

fix: service account authentication and ignore yarn config from environment variables

---

package.json
packages/shared/package.json
yarn.lock

Upgrade express from 4.20.0 to 4.21.0 to fix the vulnerability.
[CG Work Items](https://dev.azure.com/mseng/1ES/_queries/query/894c54da-1edd-4c5c-ae4d-38903314430c/)

chore: Upgraded package version for CGAlert

---

pipelines/ado-extension-validation-template.yaml

Validation Pipeline for ado-extension is failing as Azure Portal URL used for hash fragment validation is now having extra non hash fragment URLs coming along with home page when keepUrlFragment is false, so changed the validation from number of URLs scanned to hash URLs pattern scanned by crawler in index.html file
- with keepUrlFragment as false, azure portal URL with #view should not be present
- with keepUrlFragment as true, azure portal URL with #view should be present
Also increased the timeout to 5min for keepUrlFragment cases in the validation pipeline to prevent failures due to timeout.
[20241018.4](https://dev.azure.com/mseng/1ES/_build/results?buildId=29215119) build failure
- [na] Addresses an existing issue: Fixes #0000
- [na] Added relevant unit test for your changes. (`yarn …

fix: changed validation pattern for keepURLFragment cases in validation pipeline

---

pipelines/prod-release.yaml

Resolved issue in pipeline validation for CreateReleaseTag.
Pipeline was failing at validation as 1ES.DownloadPipelineArtifact@1 task is allowed only in release job, so added the job type as releaseJob ([1ES pipeline template Inputs | 1ES On EngHub](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/inputs))

fix: Resolved issue in pipeline validation for CreateReleaseTag

---

pipelines/ado-extension-validation-template.yaml

Issues in #view pages used for validation are fixed or not scanned by crawler due to maxUrl parameter.
To avoid these issues in future changing validation pattern to check any # url except #home to be present in file.
"https://ms.portal.azure.com/#home" is default routed page it will be present in both case so excluding #home routing for validation.

fix: changing validation pattern for keepurlfragment cases

---

packages/ado-extension/package.json
packages/test-website-hashroute/package.json
yarn.lock

Removing self-dependency for test-website-hashroute package as it could lead to Dependency Confusion vulnerability.
Addresses [MSRC93697 - accessibility-insights-action - Dependency Confusion vulnerability](https://portal.microsofticm.com/imp/v5/incidents/details/31000000281764/summary)

fix: Fix Dependency Confusion vulnerability

---

.github/workflows/ci.yml
packages/ado-extension/src/ado-extension-metadata.spec.ts
packages/ado-extension/task.json
pipelines/ado-extension-validation-template.yaml
pipelines/build.yaml

Node 16 left support in October 2023. Updating the code node version to node 20.x.x version. As lot of other packages are using or going to use Node 20.x.x.
Get on a supported version that we expect to last for a while

Breaking Change: Update node version to 20.x

---

pipelines/release-template.yaml

DownloadPipelineArtifact@2 task has parameter name targetPath and alias downloadPath but 1ES template specifically works with targetPath so renamed the parameter so that it can be consumed by 1ES template.

fix: renamed downloadPath parameter to targetPath

---

pipelines/package-vsix-file.yaml
pipelines/release-template.yaml

This PR is to migrated ESRP code sign-in task to use PME tenant managed identity from corp tenant app ID. The changes are made following the TSG [Integrating ESRP ADO Task into your build pipeline during Corp Migration](https://eng.ms/docs/microsoft-security/identity/trust-and-security-services/tss-high-security-environments/tss-esrp-fabric-and-platform-services/esrp-documentation/tsgs/sfi/tsg502-integrating-esrp-ado-task-into-your-build-pipeline-during-corp-migration).
Successful run of the pipeline with managed identity: [20250421.1](https://dev.azure.com/mseng/1ES/_build/results?buildId=29864324&view=logs&j=10f84eb7-256f-5ab6-3ea7-b7bd1acd1bff&t=cfda1591-f138-5aeb-4e19-bc6fa393545a)
Logs Screnshots:
Security Improvement
Below variables in the pipelines need to be updated with PME …

fix: update ESRP sign-in task to use PME managed identity
